extra.nix
flake.lock
flake.nix
lib/types-plugin.nix
modules/notes/default.nix
modules/notes/mind-nvim/default.nix

Implements the [mind.nvim](https://github.com/phaazon/mind.nvim) plugin and disables orgmode by default.
Closes #6

feat: add mind-nvim to note-taking plugins

---

docs/home-manager.adoc

With recent changes, the import was made that way : 
```nix
imports = [ neovim-flake.nixosModules.default ];
```
instead of the former :
```nix
imports = [ neovim-flake.nixosModules.hm-module ];
```
- Docs

Change hm-module to default as can be found in the code

---

flake.nix
lib/module/default.nix

From what I understand, the problem is that you can't override sets made with `neovimConfiguration`.
My solution was to get `neovimConfiguration` to `lib/module/default.nix` and just build a new package.
I did it by passing inputs to `lib/module/default.nix`, you might not want to do that, IDK.
I couldn't figure out how to add the default overlay (which contains `neovimConfiguration`) to the home manager module's pkgs (never worked with one). So i just passed inputs and got `neovimConfiguration` with that.
might also be a good idea to call it `mkNeovimConfiguration` instead?

Fix home manager module

---

docs/release-notes/rl-0.3.adoc
modules/theme/supported_themes.nix

the `vim.g.tokyonight_style` seems to be deprecated and does nothing
also added new style "moon"
from `:help tokyonight.nvim-tokyo-night-usage`:
```
colorscheme tokyonight
" There are also colorschemes for the different styles
colorscheme tokyonight-night
colorscheme tokyonight-storm
colorscheme tokyonight-day
colorscheme tokyonight-moon
```

Update tokyonight config

---

docs/release-notes/rl-0.3.adoc

After a long time, we are ready for the 0.3 release that had to be released earlier than it was meant to be, thanks to an unexpected Neovim 0.9 release. While this release brings a lot of new functionality and changes to the table, the main reason it is being released is to provide Neovim 0.9 support in the latest release for those who may be using stable releases instead of following git closely. Rest of the feature additions will be moved to the 0.4 release, which should be concluded with a breaking keybind rewrite alongside meany feature additions.
This release, of course, is vastly breaking. Most of the language options have been relocated to a new languages attribute inside the config. Caution is advised before switching.

0.3 release

---

modules/basic/config.nix
modules/basic/module.nix

the config string is written as lua instead of vimscript, and the logic is wrong anyways.
Changed the default to true because that's what neovim ships with, I could change it back if you want

fix editorconfig option

---

modules/languages/clang.nix

ccls was not using the package defined in `cfg.lsp.package`
and also was using  `cfg.lsp.cclsOpts` which doesn't exist

fix: ccls config

---

docs/release-notes/rl-0.4.adoc
modules/languages/clang.nix

adds clangd lsp as an alternative to ccls

feat: add clangd lsp

---

modules/languages/python.nix

python lsp option is written like as treesitter grammar

fix: broken python lsp option

---

modules/languages/ts.nix

Replaces eslint with eslint_d. No user-facing changes, just faster.

replace eslint with eslint_d

---

docs/custom-plugins.adoc
docs/manual.xml
docs/release-notes/rl-0.4.adoc
modules/core/default.nix

before, when you wanted to provide some kind of custom config, you had to do this:
```nix
{
configRC.aquarium-vim = inputs.neovim-flake.lib.nvim.dag.entryAnywhere "colorscheme aquarium";
}
```
with this PR, this is enough:
```nix
{
configRC.aquarium-vim = "colorscheme aquarium";
}
```
it will give the exact same result, as passing just a string to the RC will make it use nvim.dag.entryAnywhere under the hood.

feat: make it possible to use strings for the RC

---

docs/release-notes/rl-0.4.adoc
modules/lsp/config.nix

this PR fixes an issue I've had with formatting - when coding in TS, prettier would format the code fine, but so would tsserver, resulting in prettier being useless.
Before, I've tried to just filter every formatter that isn't null-ls to fix that issue, but that is not a good workaround as some languages don't have null-ls for formatting.
This pr introduces a better solution - it filters all formatters except null-ls, only when null-ls *can* format the file, which is pretty much the behaviour you'd expect.
*@horriblename could you test if this works fine for you? Thank you.*

feat: give null-ls priority over other formatters

---

modules/languages/clang.nix

#85
fixes "multiple different client offset_encodings" warning when using clangd with null-ls

fix(clangd): use same offsetEncoding as null-ls

---

docs/release-notes/rl-0.4.adoc
extra.nix
flake.lock
flake.nix
lib/types/plugins.nix
modules/debugger/default.nix
modules/debugger/nvim-dap/config.nix
modules/debugger/nvim-dap/default.nix
modules/debugger/nvim-dap/nvim-dap.nix
modules/default.nix
modules/languages/clang.nix
modules/languages/dart/config.nix
modules/languages/dart/dart.nix
modules/languages/default.nix
modules/languages/go.nix
modules/languages/python.nix
modules/languages/rust.nix
modules/modules.nix
patches/flutter-tools.patch

Add support for debug adaptor protocol (DAP) via nvim-dap.
- ~~nvim-dap-ui is kinda broken in nvim-0.9, but will be fixed in 9.1: https://github.com/rcarriga/nvim-dap-ui/issues/262~~ fixed in nvim 0.9.1
- ~~[ ] html~~
- ~~[ ] nix~~
- ~~[ ] sql~~
- ~~[ ] markdown~~
- ~~[ ] tidal~~
- ~~[ ] zig~~
I'll add basic configurations for supported languages, but I can only test go, python, rust and c/++.
[nvim-dap's Debug Adapter Installation wiki](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation)

feature: DAP support

---

docs/release-notes/rl-0.4.adoc
lib/types/plugins.nix
modules/default.nix
modules/languages/dart/config.nix
modules/languages/dart/dart.nix
patches/flutter-tools.patch

Fixes a bug where flutter-tools can't find dart binary when using a wrapped flutter package.
Patch taken from <https://github.com/FlafyDev/nixos-config>

fix(flutter-tools): bug where dart lsp is not found

---

modules/statusline/lualine/config.nix
modules/ui/breadcrumbs/breadcrumbs.nix

Prevent the buffer content from jumping around when scrolling because of disappearing lualine winbar 
https://github.com/NotAShelf/neovim-flake/assets/76622149/b1b91495-d2a4-4ce5-9de2-91ac5b52ae51

fix: jittery scrolling due to flickering winbar

---

flake.lock
flake.nix

Opening Toggleterm pushes the Bufferline on top of Nvimtree column despite the offset being set
https://github.com/NotAShelf/neovim-flake/assets/76622149/f35472b1-418a-461b-bab9-db199d1060ae
The following pull request fixes the issue and has been merged into main:
https://github.com/akinsho/bufferline.nvim/pull/657

fix: bufferline overlapping nvimtree with toggleterm

---

docs/release-notes/rl-0.5.adoc
modules/basic/module.nix

doing `"+p` instead of `p` isn't really much of a headache and I don't wanna accidentally paste images into nvim

disable useSystemClipboard by default

---

docs/release-notes/rl-0.5.adoc
flake.lock
flake.nix
lib/types/plugins.nix
modules/languages/default.nix
modules/languages/lua.nix

Adds language support (LSP + treesitter), and [neodev plugin](https://github.com/folke/neodev.nvim)
neodev is used for neovim plugin development, it adds library definitions for `vim.*`

feat: lua language support and neodev.nvim

---

modules/languages/java.nix

jdtls was missing LSP keybinds

fix: add missing on_attach for jdtls

---

docs/manual/hacking.adoc

Took me a while to figure this out
Should we rewrite/regenerate the table of contents in CONTRIBUTING.md to include the "keybinds" and "adding plugins" subsections as well?

doc: add steps to add new plugin in CONTRIBUTING.md

---

modules/default.nix

I tested it by doing 
```
neovim-flake = {
url = "github:jacekpoz/neovim-flake/plugin-thingy-deprecation";
inputs.nixpkgs.follows = "nixpkgs";
};
```
and rebuilding, it built and the plugins work

fix: stop using deprecated buildVimPluginFrom2Nix

---

docs/release-notes/rl-0.5.adoc
modules/utility/surround/config.nix
modules/utility/surround/surround.nix

The default mappings for nvim-leap and nvim-surround conflict (i.e. nvim-surround uses `S` in visual mode). This change adds options to adapt the mappings for nvim-surround directly from the surround-module.

utility/surround: Add mappings for nvim-surround

---

modules/statusline/lualine/lualine.nix

Disables LSP status inside the "toggleterm" buffer by returning "" if current buftype is toggleterm.

statusline/lualine: disable LSP status inside toggleterm buffer

---

docs/release-notes/rl-0.5.adoc
modules/languages/python.nix

Adds two additional formatters for python:
- isort, to only sort imports
- black-and-isort, which runs black + isort in a compatible manner

languages/python: add black-and-isort formatter

---

flake.lock
flake.nix
lib/types/plugins.nix
modules/statusline/lualine/supported_themes.nix
modules/theme/supported_themes.nix

Adds fork of `oxocarbon.nvim` theme with lualine support. The provided lualine does not integrate with light theme and hence it is marked as 'not well-supported'.

theme/oxocarbon: add oxocarbon theme module

---

flake.lock
flake.nix
lib/types/plugins.nix
modules/lsp/null-ls/config.nix

null-ls is unmaintained as of August 2023 (see
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621). none-ls appears to be the accepted replacement fork.

plugins: Replace null-ls with none-ls

---

modules/debugger/nvim-dap/nvim-dap.nix
modules/filetree/nvimtree/nvimtree.nix
modules/languages/clang.nix
modules/languages/dart/dart.nix
modules/languages/go.nix
modules/languages/java.nix
modules/languages/lua.nix
modules/languages/nix.nix
modules/languages/php.nix
modules/languages/python.nix
modules/languages/rust.nix
modules/languages/sql.nix
modules/languages/svelte.nix
modules/languages/ts.nix
modules/languages/zig.nix
modules/lsp/nvim-code-action-menu/nvim-code-action-menu.nix
modules/lsp/trouble/trouble.nix
modules/notes/orgmode/orgmode.nix
modules/projects/project-nvim/project-nvim.nix
modules/terminal/toggleterm/toggleterm.nix
modules/ui/borders/borders.nix
modules/visuals/visuals.nix

I noticed a few oddly phrased descriptions for enable options in the docs.
mkEnableOption already adds the phrase "Whether to enable ..." to the beginning of the option description, such that the string argument should only be "thing to be enabled"
Also, sorry for the PR spam :grimacing:

fix enable option descriptions

---

docs/release-notes/rl-0.5.adoc
modules/lsp/config.nix
modules/lsp/module.nix

This exposes the keybindings for the lsp commands to the configuration and maps a few more commands (e.g. `vim.lsp.buf.format()`) It also adds a description to be picked up by whichkey to make the whichkey UX a bit nicer (ie. we're now showing "Go to definition" instead of just "vim.lsp.buf.definition()")

lsp: make key bindings configurable

---

docs/release-notes/rl-0.5.adoc
modules/lsp/config.nix
modules/lsp/module.nix

allows disabling format on save at runtime with `let b:formatsave = v:false`

feat: allow disabling format on save per buffer

---

docs/release-notes/rl-0.5.adoc
lib/lua.nix
modules/statusline/lualine/config.nix
modules/statusline/lualine/lualine.nix

I have a usecase where I need to add an additional source to a section in the statusline. Since repeating and then extending the current defaults isn't very convenient, I've changed the type of `activeSection`s and `inactiveSection`s attributes to `listOf str`, added `extraActiveSection` and `extraInactiveSection` of the same type and then create a lua table from the concatentation of both settings in the config.
I immediately see two issues with this:
1. I am breaking existing configurations that customize the lualine sections
2. Having a nix-list of lua-values is a bit odd. Eg. adding a string would look like ``["'some_string'"]` :shrug: 
I'm not sure if (1.) is a problem. You're on 0.x still so I assume it's justifiable, but I'm of course willing to adapt this PR if you prefer a proper …

statusline/lualine: extensible sections

---

configuration.nix
docs/release-notes/rl-0.5.adoc
flake.lock
flake.nix
lib/types/plugins.nix
modules/lsp/default.nix
modules/lsp/nvim-docs-view/config.nix
modules/lsp/nvim-docs-view/default.nix
modules/lsp/nvim-docs-view/nvim-docs-view.nix

A neovim plugin to display LSP hover documentation in a side panel, pretty similar to the VSCode extension [Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view)

modules/lsp: add nvim-docs-view

---

modules/lsp/nvim-docs-view/config.nix
modules/lsp/nvim-docs-view/nvim-docs-view.nix

Neglected the toggle and update keybinds last time. This PR fixes that.

lsp/nvim-docs-view: add keybinds

---

docs/default.nix
docs/man-configuration.xml
docs/manual.xml
docs/manual/hacking.adoc
docs/release-notes/rl-0.5.adoc
lib/default.nix
lib/stdlib-extended.nix
lib/types/plugins.nix
modules/autopairs/nvim-autopairs/nvim-autopairs.nix
modules/completion/nvim-cmp/nvim-cmp.nix
modules/core/default.nix
modules/filetree/nvimtree/nvimtree.nix
modules/statusline/lualine/lualine.nix
modules/treesitter/context.nix
modules/treesitter/treesitter.nix
modules/ui/breadcrumbs/breadcrumbs.nix
modules/visuals/visuals.nix

NixOS 23.11 is deprecating DocBook option documentation. Following home-manager in this change is probably a good idea. This change drops `literalDocBook` and the provided nmd functions in favor of nixosOptionDocs and CommonMark in option descriptions.

docs: use nixosOptionDocs

---

configuration.nix
docs/release-notes/rl-0.5.adoc
flake.lock
modules/visuals/config.nix
modules/visuals/visuals.nix

Updates indent-blankline to v3 and removes the workaround requiring `vim.wo.colorcolumn = "99999"` - reported to be fixed upstream in neovim.
I've renamed some of the module options, and I'd *really* like to use `lib.mkRemovedOptionModule` and `lib.mkRenamedOptionModule`, however, both of those cause the build system to assert the files they are defined in (wherever they are) are not actually modules.

modules/visuals: update indent-blankline to v3

---

modules/statusline/lualine/config.nix

Fixes bug where an empty winbar is shown even when breadcrumbs are disabled

fix: disable empty winbar when breadcrumbs are disabled

---

flake.lock

Updates all plugin inputs to their latest versions. No breaking API changes, but new features might have been added in the duration in which they haven't been updated. A long sweep will be necessary after #181 is finished.

flake: bump all plugin inputs

---

lib/types/default.nix
lib/types/plugins.nix

closes #133 
I started playing around with the idea a bit more. will try to convert the bigger plugins first to get a grasp on how it would go
progress (by directories in `modules/`)
random bugs I found:
1. telescope: all the options should be under `defaults` but most are not
2. lualine: `extensions` should not be under `options`

lib: function for custom plugin `setup()` arguments

---

configuration.nix
docs/release-notes/rl-0.6.md
flake.lock
flake.nix
lib/types/plugins.nix
modules/rich-presence/default.nix
modules/rich-presence/neocord/config.nix
modules/rich-presence/neocord/default.nix
modules/rich-presence/neocord/neocord.nix

Presence.nvim hasn't been updated in around 2 years and in my testing, I've noticed that it does not work with the latest versions of arRPC. Replaced it with the more up-to-date neocord.
Minor changes to the module definitions. Mostly the same, but some options (such as buttons) are removed entirely.

modules/rich-presence: deprecate presence-nvim in favor of neocord

---

modules/rich-presence/neocord/config.nix

Fixes nil being passed as string literal to neocord's setup log_level option.

rich-presence/neocord: fix log_level config

---

docs/release-notes/rl-0.6.md
modules/languages/markdown/config.nix
modules/languages/markdown/markdown.nix

I don't know if it's good practice to combine two commits into one PR like this, but they both touch on the same module, so I figured it would probably be okay. Correct me if I'm wrong.
The first commit adds marksman as a markdown LSP. It also provides the same options that the other language modules do.
The second commit fixes Glow, which I noticed wasn't working correctly (or at all). As with the first commit, new option(s) are provided. There is now an option for changing the preview keybind, which by default is the same bind that it was before (\<Leader>p).
- Bug fix (I guess. Glow not working hasn't been reported as an issue, though)
- New feature
The maximal config completely fails to build for me, so I replaced it with my own. When using my own, I get no new errors, nor any new …

Language/markdown: Added LSP and fixed Glow not working

---

configuration.nix
docs/release-notes/rl-0.6.md
modules/languages/css.nix
modules/languages/default.nix
modules/languages/tailwind.nix

Adds support for CSS and Tailwindcss.
From what I can tell, Tailwindcss likely depends on css treesitter, but I do not want those two modules to be codependent on each other.

languages: add css and tailwind language support

---

docs/release-notes/rl-0.6.md
modules/statusline/lualine/config.nix
modules/statusline/lualine/lualine.nix

Adds module options for `always_divide_middle`, `ignore_focus` and `disabled_filetypes` configuration options of Lualine.

statusline/lualine: avoid hardcoding config options

---

modules/dashboard/startify/config.nix

For some reason I've used `pkgs.neovimPlugins` instead of `pkgs.vimPlugins`. There is no such thing as `pkgs.neovimPlugins`.
Closes #208

dashboard/startify: fix invalid reference to "neovimPlugins"

---

docs/release-notes/rl-0.6.md
flake.lock
flake.nix
modules/ui/colorizer/colorizer.nix
modules/ui/colorizer/config.nix

~~Added a new option for colorizer which, when enabled, will attach colorizer to any buffer with a filetype set in autoAttach.filetypes. I also fixed the indentation on colorizer's DEFAULT_OPTIONS.~~
Rebased colorizer.nvim on a maintained fork and updated the options accordingly.
- New feature

ui/colorizer: rebase on maintained fork

---

modules/filetree/nvimtree/nvimtree.nix

Makes the default `systemOpen` option platform specific.

filetree/nvimtree: fix default systemOpen on darwin

---

docs/release-notes/rl-0.6.md
flake.lock
flake.nix
lib/types/plugins.nix
modules/theme/supported_themes.nix

Added rose-pine as a theme.
I don't think I missed anything, but please tell me if I did.
* New feature (non-breaking change which adds functionality)
Screenshots & Logs
(the git tree was only dirty because I was testing the theme)
I couldn't figure out how to get the docs to update the styles list, but the themes work.

Theme: add `rose-pine`

---

docs/release-notes/rl-0.6.md
modules/utility/preview/glow/glow.nix

Adds the missing documentation entry for #217, and ensures the changes are backwards compatible through the usage of `mkRenamedOptionModule` to warn the users that have the old option still defined instead of erroring out.

docs: add missing documentation entry; define renamed options

---

lib/lua.nix

fixes two bugs with null conversions:
1. `expToLua` converts null to null (should be nil)
2. `toLuaObject` converts null to ""

Fix lua null conversion

---

docs/release-notes/rl-0.6.md
modules/core/default.nix
modules/default.nix

Introduces a `vim.luaPackages` option to be passed to the wrapper to include additional Lua packages.

wrapper: provide option to wrap neovim with extra lua packages

---

docs/release-notes/rl-0.6.md
flake.lock
flake.nix
modules/visuals/config.nix
modules/visuals/default.nix
modules/visuals/fidget/config.nix
modules/visuals/fidget/default.nix
modules/visuals/fidget/fidget.nix
modules/visuals/visuals.nix

Updates `fidget.nvim` to use the rewritten configuration options.  Also uses #181.
Opening it up as a draft PR because I still need to figure out how to handle the commented out options.

visuals/fidget: migrate to new configuration

---

modules/utility/images/image-nvim/config.nix

The assert was added because in my testing `ueberzug` backend was not working in Neovim. 
After several wasted hours of digging through the source code of `ueberzugpp`, found out that `iterm2` image protocol included in Wezterm (internally used by `ueberzugpp`) is not supported by `image.nvim`. Taking a look at the closed issues, found the issue about it https://github.com/3rd/image.nvim/issues/86.
I still chose to keep the option disabled in all default configurations as it requires an external program and still might abort on some terminals such as Alacritty.

images/image-nvim: remove assert for `ueberzug` backend on darwin

---

docs/release-notes/rl-0.6.md
modules/default.nix
modules/neovim/mappings/default.nix
modules/neovim/mappings/options.nix
modules/wrapper/build/options.nix
modules/wrapper/rc/options.nix

- Exposes more basic wrapper features (such as `withRuby`, `withNodeJs`, `withPython3`, and `python3Packages`) to the user configuration.
- Performs internal refactoring to make `modules` directory more readable and easily traversable.
- Adds `extraPackages`, which takes a list of packages, that will be passed to the wrapper's `PATH` during build.

modules: clean up wrapper; extra wrapper features

---

lib/types/plugins.nix

Coercion was kinda buggy and makes `either str luaInline` ambiguous.

Remove str to luaInline coercion

---

configuration.nix
modules/plugins/languages/default.nix
modules/plugins/languages/typst.nix

Adds support for typst with `typst-lsp` LSP and `typstfmt` as the default formatter.
Contributor: ItsSorae

languages/typst: add typst language support

---

configuration.nix

Wakatime errors on startup because it requires an API key and gets in the way when testing out your changes. So I suggest we disable it in the maximal output.

configuration: disable wakatime in maximal output

---

.github/FUNDING.yml

I initially removed the ability to fund me due to this project being a soft-fork of JordanIsaac's neovim-flake. However, the project has changed *enough* to justify it being a standalone and therefore unaffiliated project. With the number of commits and the time spent in mind, I am allowing funding again.

nvf: let people pay me

---

docs/release-notes/rl-0.7.md
modules/plugins/visuals/fidget/fidget.nix

Changes `display.overrides` to use `submodule` instead of `anything` for better eval time checks.

visuals/fidget: use submodule for notification group overrides

---

flake/modules/home-manager.nix
flake/modules/nixos.nix

I will deprecate it in a future date, but for now it is fine.

flake/modules: alias `programs.nvf` to `programs.neovim-flake`

---

docs/release-notes/rl-0.7.md
modules/plugins/lsp/config.nix

Adds a check to filter out null mappings in local function `mkBinding`.
It is only an issue with the LSP module because it doesn't use `genMaps` to generate the mappings and therefore doesn't filter them out automatically.
Fixes #281

plugins/lsp: filter out null mappings

---

docs/release-notes/rl-0.7.md
flake.lock
modules/wrapper/rc/config.nix
modules/wrapper/rc/options.nix

* Adds `vim.additionalLuafiles`
Allows the user to specify a list of lua files that will be called via `luafile`. All paths
that are passed to this option are checked by `builtins.isPath` so attempting to source paths
that do not exist do not result in a broken Lua configuration.
* Bumps flake inputs to their latest version (might fix nil timing out on large directories)

wrapper/rc: add vim.extraLuaFiles

---

configuration.nix
docs/release-notes/rl-0.7.md
modules/plugins/languages/default.nix
modules/plugins/languages/ocaml.nix

this adds support for the ocaml lsp and formatter
everything seems to be working, the only issue is the lsp gives me a warning about not being able to find the formatter on format:
but it still formats so ¯\\\_(ツ)\_/¯
I think it could be fixed by adding `ocamlformat` to nvf's environment but I don't know how to do that sowwy uwu

add ocaml support

---

flake.lock
flake.nix

This moves our nixpkgs instance to `nixos-unstable-small` (previously `nixos-unstable`) to help get package updates faster, and potentially reduce eval times as certain packages (I think generally graphical toolkits) are excluded.
Additionally, it bumps all plugin inputs to help with Neovim 0.10.0 compatibility, which just landed in the unstable channel.

flake: switch to nixos-unstable-small

---

docs/release-notes/rl-0.7.md
lib/lua.nix
modules/wrapper/rc/config.nix

there is a single use of `__empty` in the codebase, I need to double check what it's doing before I remove it

lib: do not filter out empty attrs in toLuaObject

---

flake.lock
flake.nix

`nixos-unstable-small` seems to not cache macOS builds anymore, so building requires rebuilding the world. I am not sure why it ever included macOS builds, or how it worked previously but nonetheless it is broken now.

flake: switch nixpkgs branch to nixpkgs-unstable

---

flake.lock
modules/plugins/notes/orgmode/config.nix

removes the deprecation warning and shit, treesitter for org files still works

plugins/orgmode: remove deprecated ts setup call

---

configuration.nix
docs/release-notes/rl-0.7.md
modules/plugins/ui/smartcolumn/smartcolumn.nix

ui/smartcolumn: change `custom_colorcolumn` type to expected type string

---

modules/plugins/autopairs/nvim-autopairs/config.nix

Not that important, but I didn't realize that function existed before

modules/autopairs: use boolToString instead of toLuaObject

---

docs/release-notes/rl-0.7.md
flake.lock
flake.nix
modules/plugins/languages/go.nix

The previous configuration is pretty much useless, relying on dap-go gives us a better out-of-the-box experience

Use dap-go for dap configurations

---

docs/release-notes/rl-0.7.md
modules/default.nix

The `runCommand` doesn't pass src and version attributes to its underlying `mkDerivation`. This causes the `flutter-tools` source to be empty, and thus Neovim fails to load the module at runtime.
Here is the error and directory contents for reference:
```
Error detected while processing pre-vimrc command line:
E5113: Error while calling lua chunk: vim/_editor.lua:0: pre-vimrc command line..script nvim_exec2() called at pre-vimrc command line:0../nix/store/n3cwd61i9mg0yc5f8303yg1hrfqnhpyh-init.vim, line
1507: Vim(lua):E5108: Error executing lua [string ":lua"]:580: module 'flutter-tools' not found:
no field package.preload['flutter-tools']
no file '/nix/store/dd95xbhig1gplwzhr1vi98cgjfwfm41v-luajit-2.1.1713773202-env/share/lua/5.1/flutter-tools.lua'
no file …
```

modules: fix unused src and version attrs in buildPlug

---

modules/wrapper/rc/options.nix

while the previous solution did add the additional paths to runtimepath, their `plugin/` dir was not sourced for whatever reason. This is the intended usage according to the help file anyway so I'm following it

wrapper: fix additionalRuntimePaths lua script

---

docs/manual/configuring/dag-entries.md
modules/plugins/theme/theme.nix
modules/wrapper/rc/config.nix

This is needed, since the DAG order breaks for users who don't use the builtin theming options.

treewide: remove the theme section from the DAG order dependance

---

docs/release-notes/rl-0.7.md
modules/plugins/utility/telescope/config.nix
modules/plugins/utility/telescope/telescope.nix

The projects command had a typo preventing it from working; the keybinding description was the same as for Telescope files. 
Added `<leader>fr` for Telescope resume per default.
Oh, and refactored duplicate top level `vim.` attributes, which is a "style" error flagged by `statix` and didn't seem to have a reason in this case.

Telescope: fix projects binding, add Telescope resume in default

---

docs/release-notes/rl-0.7.md
modules/plugins/statusline/lualine/config.nix
modules/plugins/ui/breadcrumbs/breadcrumbs.nix

Adds `vim.ui.breadcrumbs.lualine.winbar.enable` to control winbar component behaviour, and moves `vim.ui.breadcrumbs.alwaysRender` (whether to always render the winbar compontent) to `vim.ui.breadcrumbs.lualine.winbar.alwaysRender`

ui/breadcrumbs: allow lualine winbar component to be disabled

---

modules/neovim/init/basic.nix

`vim.undoFile.enable` and `vim.undoFile.path` can be used to manipulate whether undofile will be enabled, and the location if it is enabled.
Closes #331

neovim/basic: add undofile options

---

flake.lock
modules/plugins/languages/ts.nix

Small improving steps, just like chess.

languages/ts: update lspconfig; rename tsserver to ts_ls

---

docs/manual/configuring/dag-entries.md
modules/wrapper/rc/config.nix
modules/wrapper/rc/options.nix

- **wrapper/rc: add `vim.options`**
- **docs: document addition of optionsScript**
Adds `vim.options` to easily configure `vim.o` values.

modules/wrapper: add `vim.options`

---

docs/release-notes/rl-0.7.md
modules/plugins/utility/surround/config.nix
modules/plugins/utility/surround/surround.nix

Modifies the nvim-surround module to use setupOpts, and define the alternate binds in setupOpts as well.
---

Surround setupopts

---

lib/types/plugins.nix

idk why I made setupOpts `attrsOf anything` instead of `anything`

lib: remove pointless type restriction

---

modules/plugins/comments/comment-nvim/config.nix

Trivial change, fixes the incorrect map modes for the visual Comment.nvim binds.

comment-nvim: fix visual mappings

---

docs/release-notes/rl-0.7.md
modules/plugins/languages/nix.nix

Replaced nixpkgs-fmt with nixfmt-rfc-style, as the former has been deprecated for a few years.

languages/nix: change nixpkgs-fmt to nixfmt (rfc-style)

---

docs/release-notes/rl-0.7.md
modules/plugins/lsp/otter/config.nix
modules/plugins/utility/motion/leap/leap.nix

Fixed typo in otter's setupOpts
---

Fix typo in otter setupOpts

---

configuration.nix
docs/release-notes/rl-0.7.md
flake.lock
flake.nix
modules/plugins/languages/csharp.nix
modules/plugins/languages/default.nix
modules/plugins/languages/kotlin.nix
modules/plugins/languages/nix.nix
modules/plugins/lsp/config.nix

Cleans up some stuff and adds a csharp language module under `vim.languages.csharp`
---

languages/csharp: init

---

modules/plugins/utility/preview/markdown-preview/config.nix

`MarkdownPreview` has not been working for some time now, even with a standard config:
```nix
utility = {
preview.markdownPreview = {
enable = true;
autoStart = true;
lazyRefresh = true;
};
...
};
```
I would consistently get this error:
The changes in this PR simplify the nix module while at the same time adhering better to the upstream documented config (i.e. empty strings as "unconfigured" values for `mkdp_open_ip` and `mkdp_port`).
With the included fix `mkdp` works again.
---
[reaction]: …

fix markdown-preview config error

---

configuration.nix
docs/release-notes/rl-0.7.md
modules/plugins/languages/default.nix
modules/plugins/languages/julia.nix

languages/julia: init

---

configuration.nix
docs/release-notes/rl-0.7.md
modules/plugins/languages/default.nix
modules/plugins/languages/vala.nix
modules/plugins/utility/preview/markdown-preview/config.nix

Add support for Vala language
---

languages/vala: init

---

docs/release-notes/rl-0.7.md
modules/plugins/languages/typst.nix

Added tinymist and enabled formatters
---

typst: added tinymist and activated formatters

---

modules/plugins/visuals/nvim-web-devicons/nvim-web-devicons.nix

accidentally disabled in a6bb6e1b3e360a1222bdc877633ac37440f1d4d2

nvim-web-devicons: re-enable icon color

---

configuration.nix
docs/release-notes/rl-0.7.md
modules/plugins/languages/asm.nix
modules/plugins/languages/default.nix

Adding support for Assembly
---

languages/assembly: init

---

modules/plugins/completion/nvim-cmp/config.nix
modules/plugins/completion/nvim-cmp/nvim-cmp.nix

Moves text and snippet completions to the bottom by default. It feels like a hack to do this, but I can't find a better way to get around this. If anyone has suggestions on what the ordering should look like, please let me know.
I was thinking about adding the `recently_used` and `locality` comparators to the defaults, but they seem a little too opinionated/performance-heavy, so I didn't.
---
[pull requests you …

nvim-cmp: move text and snippet completions to the bottom

---

docs/release-notes/rl-0.7.md
modules/plugins/languages/r.nix

Adds Formatters for the R module
---

languages/r: added formatters

---

docs/release-notes/rl-0.7.md
modules/plugins/utility/binds/which-key/config.nix

Changes which-key to the new spec
---

binds/which-key: changing to the new spec

---

docs/release-notes/rl-0.7.md
flake.lock
flake.nix
modules/plugins/visuals/default.nix
modules/plugins/visuals/tiny-devicons-auto-colors/config.nix
modules/plugins/visuals/tiny-devicons-auto-colors/default.nix
modules/plugins/visuals/tiny-devicons-auto-colors/tiny-devicons-auto-colors.nix

visuals/tiny-devicons-auto-colors: init module

---

modules/plugins/completion/nvim-cmp/config.nix

nvim-cmp: fix use of mkDefault for borders

---

modules/plugins/languages/typst.nix

Applies widespread solution to stop annoying error message in typst whenever using non-english characters.
nix fmt is temporarlity broken on my system (or I'm sleep deprived and used it wrong. Could be), but I have used the nix formatter within the file and it should pass the formatter checks.
---

languages/typst: fix callback error with non-english characters

---

modules/wrapper/lazy/config.nix
modules/wrapper/lazy/lazy.nix

- checks that the provided name (`vim.lazy.plugins.<name>`) is same as package.pname
- if a custom load function is given this check is bypassed because they probably know what they're doing
- allow null package for more advanced uses (like auto-loading nvim's optional plugins)
---

lazy: add assertions against common problems

---

docs/release-notes/rl-0.4.md
docs/release-notes/rl-0.7.md
modules/extra/deprecations.nix
modules/neovim/init/basic.nix
modules/wrapper/rc/options.nix

Less DAGs, more customizability.
Moves interpolated basic vim options into `vim.options` with a backwards compatible interface. I'm fully intending to deprecate all of the options before merge.
---

neovim/init: set basic options via `vim.options`

---

docs/manual/hacking/keybinds.md
docs/release-notes/rl-0.7.md
lib/binds.nix
modules/plugins/comments/comment-nvim/config.nix
modules/plugins/debugger/nvim-dap/config.nix
modules/plugins/filetree/nvimtree/config.nix
modules/plugins/lsp/trouble/config.nix
modules/plugins/terminal/toggleterm/config.nix
modules/plugins/utility/motion/leap/config.nix
modules/plugins/utility/telescope/config.nix

note: we don't need to wait for this PR to release v0.7, I'm putting this up to let yall see if you like the new lib.
adds a less abstracted helper function and removes the horrible ones targeting `vim.keymaps`
---

internal: simpler helper functions for keymaps

---

configuration.nix

Disable some uncommon language modules that are not critical to maximal
configuration. Although it is _supposed_ to be a large configuration, we can
live without fetching as many dependencies as we currently do.
Also adds a few comments to the demo configuration.

configuration: disable superfluous language modules in maximal

---

configuration.nix
docs/release-notes/rl-0.8.md
flake.lock
flake.nix
modules/plugins/languages/default.nix
modules/plugins/languages/haskell.nix
modules/plugins/languages/rust.nix

This adds Haskell QOL to nvf, successor PR to #426.
More specifically, this uses haskell-tools.nvim to handle LSPs and DAPs. Null-ls doesn't have defaults for Ormolu nor Fourmolu so formatting there has not been complete as of yet.
Manually tested (x86_64-linux), doesn't work right now because I keep having GitHub rate limit me trying to update the flake. (causes mnw to shit the bed trying to find `src` among the list of plugins.)
Going as a draft for now but you can make your reviews, if any extra info is needed then please comment on that.

plugins/languages: add haskell support

---

modules/plugins/languages/ts.nix

Prevent ts_ls from touching the formating.
ts_ls is supposed to be used as a lsp, and prettier as a formatter. 
In the current situation, ts_ls has the last word over prettier and applies changes such as adding spaces between empty curled braces. 
`{}` -> `{ }`
With this PR, ts_ls is still enabled but is prevented from using formatting.
--- …

ts_ls: prevent from formatting

---

modules/plugins/languages/haskell.nix

#499 had introduced some breakage involving the Haskell DAP option. Turns out it was because I forgot to encapsulate the command with `{""}`. This PR fixes that error so now the DAP doesn't cause issues.
I have fully tested the module, including DAP support and just about any extras I could think of.

languages/haskell: fix DAP command definition

---

modules/plugins/ui/notifications/nvim-notify/config.nix

Avoids [a check](https://github.com/rcarriga/nvim-notify/blob/fbef5d32be8466dd76544a257d3f3dce20082a07/lua/notify/init.lua#L189-L195) that shouldn't exist in the first place. I ran into an issue while developing my plugin where vim.notify would return nil instead of what the other branch would, and it's pretty miraculous I found the problem to be honest. The edge cases the check handles should already be handled by plugins. If nvf some part of nvf relied on this, then that part would break without nvim-notify enabled, and if some part of the user's config relied on this then it would be really annoying if something seemingly unrelated broke when they disabled nvim-notify.

nvim-notify: use explicit function for vim.notify

---

flake.lock

Fixed an annoying bug that would cause <cwd>/.git to be used as the actual cwd

flake: update run.nvim

---

flake.lock

Updates all plugins to their latest versions. 
Built with `nix` and `maximal` packages, no new errors are generated.

flake: bump all inputs

---

docs/release-notes/rl-0.8.md
flake.lock
flake.nix
modules/plugins/languages/markdown.nix

As requested by @deviantsemicolon. Adds render-markdown.nvim to the markdown module as an extension. Ideally the last time we change the language module to avoid making the upcoming language refactor more difficult.

languages/markdown: add `render-markdown.nvim` as an extension

---

docs/release-notes/rl-0.8.md
modules/plugins/git/gitsigns/config.nix
modules/plugins/git/gitsigns/gitsigns.nix

Adds `vim.git.gitsigns.setupOpts` for user-specified setup table. We do not provide any defaults, as we did not do so previously and users may add their own options easily.

git/gitsigns: migrate to `setupOpts`

---

modules/plugins/languages/haskell.nix

This specifies the `--lsp` flag when running `haskell-language-server-wrapper`. This allows HLS to run as an LSP instead of checking the file. Another silly one line fix :^).

languages/haskell: specify lsp flag

---

docs/release-notes/rl-0.8.md
modules/plugins/notes/obsidian/obsidian.nix

As the `obsidian.nvim` readme describes, the `dir` option is provided for backwards compatibility. The problem with this is that because `nvf` defines this value (*with* a default value), means that it overrides the `workspaces` option, making it impossible to use. Removing it would keep the same functionality, just without the default.

notes/obsidian: remove default dir-value

---

modules/plugins/utility/telescope/config.nix

force a reload when telescope is loaded to workaround #535
doesn't fully address the issue (telescope is still in a loaded-but-not-configured state until
keybind is triggered)
---

telescope: workaround nixpkgs extensions breaking :Telescope

---

configuration.nix
docs/release-notes/rl-0.7.md
lib/languages.nix
modules/neovim/init/spellcheck.nix
modules/wrapper/rc/options.nix

And some other fixes. Not necessarily proud of the spellcheck one, but it beats taking an unchecked string.

various: address diniamo's review comments

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/markdown.nix

Adds prettierd as a formatter option.
This would be made a lot easier by #382, but before that is complete, this looks like the best way to do it.

languages/markdown: add prettierd formatter

---

docs/release-notes/rl-0.8.md
modules/plugins/snippets/luasnip/config.nix
modules/plugins/snippets/luasnip/luasnip.nix

Added setupOpts to `vim.snippets.luasnip`.
Right now, there is a soft dependency on nvim-cmp, because setting `lazy = true`, makes it so that it won't load if nvim-cmp is not present and configured. I will not fix that in this pr, as users can set `vim.lazy.plugins.luasnip.event = "BufEnter"` themselves.

snippets/luasnip: add setupOpts

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/default.nix
modules/plugins/languages/wgsl.nix

Adds Treesitter and LSP support for WebGPU Shading Language

languages/wgsl: init module

---

configuration.nix
docs/release-notes/rl-0.8.md
modules/plugins/languages/default.nix
modules/plugins/languages/ruby.nix

Ruby is a pain, but I think some basic support is better than nothing and can be improved on.
At the moment, formatters only work if .rubocop.yml contains no extensions, as most of those are not available through nixpkgs yet.
This is my first nix PR so please be thorough.
---

languages/ruby: add ruby support

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/python.nix

This PR adds support to using `ruff` as a formatter for Python.

languages/python: add ruff formatter

---

docs/release-notes/rl-0.8.md
flake.lock
flake.nix
modules/plugins/statusline/lualine/supported_themes.nix
modules/plugins/theme/supported-themes.nix

For Issue https://github.com/NotAShelf/nvf/issues/557
Fixes #557

feat: add nord theme

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/nix.nix

Removes the hardcoded 2-wide indentation from Nix filetype. To replicate previous behaviour, user must consolidate indentation behaviour to the Editorconfig configuration, or use autocommands in raw lua configuration.
Example:
```lua
vim.api.nvim_create_autocmd("FileType", {
pattern = "nix",
callback = function(opts)
local bo = vim.bo[opts.buf]
bo.tabstop = 2
bo.shiftwidth = 2
end
})
```
While feedback for this "sane" default has been mostly positive, nvf has no place setting opinionated defaults that are difficult to override. Fixes #564

languages/nix: remove hardcoded indentation options

---

flake.lock

Get the Treesitter bump from upstream, and update all plugins to their latest versions. 
No breakage internally, user configurations may need to be updated according to `setup` changes to individual plugins.

flake: bump nixpkgs; bump plugin inputs

---

docs/release-notes/rl-0.8.md
modules/neovim/init/default.nix
modules/neovim/init/highlight.nix

Creates options for configuring highlight groups, mirroring the options available in `nvim_set_hl`.

highlight: init

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/zig.nix

Implemented DAP support for zig. Included comment regarding redundant `dap.adapters.lldb` code when both clang and zig dap modules are enabled. Redundant code does NOT break when both clang and zig dap are enabled during tests.
---

languages/zig: Added dap support

---

docs/man/header.5
docs/man/nvf.1

Fixes #554 
Adds `nvf-print-config` and `nvf-print-config-path` to the nvf manpages and improves wording & layout a little bit. The options page also mentions the online manual for additional information.

docs: improve manpages; mention helpful utilities

---

configuration.nix
docs/release-notes/rl-0.8.md
flake.lock
flake.nix
modules/plugins/utility/default.nix
modules/plugins/utility/yanky-nvim/config.nix
modules/plugins/utility/yanky-nvim/default.nix
modules/plugins/utility/yanky-nvim/yanky-nvim.nix

Adds [Yanky](https://github.com/gbprod/yanky.nvim) for an improved yanking experience.
Includes a sample option for `ring.storage` to automatically handle sqlite dependency if the selected backend is sqlite.
Closes #574

utility/yanky-nvim: init

---

modules/plugins/languages/ts.nix

languages/ts: register javascript with prettier formatter

---

.editorconfig
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/README.md
configuration.nix
docs/manual.nix
docs/manual/options.md
docs/manual/tips.md
docs/manual/tips/debugging-nvf.md
docs/manual/tips/lua-configuration.md
docs/manual/tips/pure-lua-config.md
flake.nix
flake/packages.nix
flake/templates/default.nix
flake/templates/standalone/flake.nix
lib/dag.nix
release.json

Touches up documentation for the purpose of a general cleanup (language, examples, etc.) and mentions somewhat obscure tips and tricks/features in project synopsis (README) and the manual, such as the manpages for offline documentation.

treewide: general cleanup in docs and contribution exp.

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/nix.nix

This PR introduces a new language server for nix, [nixd](https://github.com/nix-community/nixd).
---

languages/nix: add nixd

---

docs/release-notes/rl-0.8.md
flake.lock
flake.nix
flake/legacyPackages.nix
flake/legacyPackages/blink-cmp.nix
flake/overlays.nix
modules/plugins/completion/blink-cmp/blink-cmp.nix
modules/plugins/completion/blink-cmp/config.nix
modules/plugins/completion/blink-cmp/default.nix
modules/plugins/completion/config.nix
modules/plugins/completion/default.nix
modules/plugins/completion/module.nix
modules/plugins/completion/nvim-cmp/config.nix
modules/plugins/lsp/config.nix
modules/plugins/lsp/lsp-signature/config.nix
modules/plugins/lsp/lspkind/config.nix
modules/plugins/notes/obsidian/obsidian.nix
modules/plugins/snippets/luasnip/config.nix
modules/plugins/treesitter/config.nix
modules/wrapper/build/config.nix
modules/wrapper/build/packages/blink-cmp.nix

added blink.cmp
~~- [ ] update script~~ (used `allowBuiltinFetchGit` instead)

completion/blink.cmp: add

---

modules/plugins/visuals/rainbow-delimiters/config.nix

The migration to npins broke the reference to `rainbow-delimiters`.
This fixes it.
---

rainbow-delimiters: fix startPlugins name

---

docs/release-notes/rl-0.8.md
modules/plugins/lsp/lspkind/config.nix

Fixes the lspkind plugin name after the change to npins.
---

lsp/lspkind: fix plugin name

---

modules/plugins/languages/dart.nix

Small fix that changes `flutter-tools` to `flutter-tools-nvim`

languages/flutter: update package name to match pin

---

modules/plugins/utility/surround/surround.nix

Removed extra 'e' from the word upstream in description
---

nvim-surround: Fix typo in description

---

docs/release-notes/rl-0.8.md
modules/plugins/git/default.nix
modules/plugins/git/git-conflict/config.nix
modules/plugins/git/git-conflict/default.nix
modules/plugins/git/git-conflict/git-conflict.nix
npins/sources.json

Addition of the [git-conflict](https://github.com/akinsho/git-conflict.nvim) plugin. A plugin for visualizing/managing git conflicts in nvim.
I have made so it gets automatically enabled when `vim.git.enable` is set, like with `gitsignes` and `vim-fugitive`.
--- …

plugins/git: add git-conflict-nvim

---

flake.nix
flake/modules/home-manager.nix
flake/modules/nixos.nix

fixes #635 
to illustrate the problem, see this example flake.nix:
```nix
{
inputs = { /* ... */ };
outputs = {nixpkgs, ...}@inputs: {
testing = {
a = inputs.self             # valid
b = inputs.self.inputs      # valid
c = inputs.self.inputs.self # does not exist
};
};
}
```
prior to this change, inputs.self.inputs was passed to the hm
module, which lacks the self attr
This change passes in the "top-level" inputs instead.

blink: fix missing inputs.self in HM and NixOS modules

---

docs/release-notes/rl-0.8.md
modules/plugins/git/git-conflict/git-conflict.nix

The current default git-conflict keybinds _conflicts_ with vim's builtin keybinds. This PR prefixes
them with the `<leader>` key

git/git-conflict: avoid shadowing builtin keybinds

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/default.nix
modules/plugins/utility/yanky-nvim/config.nix
modules/plugins/utility/yanky-nvim/yanky-nvim.nix
modules/plugins/utility/yazi-nvim/config.nix
modules/plugins/utility/yazi-nvim/default.nix
modules/plugins/utility/yazi-nvim/yazi-nvim.nix

- **utility/yazi-nvim: init**
- **utility/yanky-nvim: fix plugin setupOpts; assert when shada is disabled**
Adds `vim.plugins.utility.yazi-nvim`, and a bunch of default keybinds for it.
Additionally, fixes some minor oversight in Yanky setup that managed to slip by.
Closes #585
--- …

utility/yazi-nvim: init

---

modules/wrapper/lazy/lazy.nix

not-so-recently lz.n started treating `lazy = false` as "do not lazy-load" and
we default to `false`, hence nothing is lazy-loaded in #663
---

lazy/lz.n: fix default un-lazy plugins

---

modules/plugins/lsp/nvim-docs-view/nvim-docs-view.nix

Default mappings of plugin nvim-docs-view conflict with directional navigation in normal mode. This PR prefixes the keybindings with the leader key.

plugins/nvim-docs-view: fix default mappings (#675)

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/yazi-nvim/config.nix
npins/sources.json

Add `yazi.nvim` dependency [`snacks.nvim`](https://github.com/folke/snacks.nvim/). 
`:checkhealth yazi` was warning about a missing dependency, and project `README` recently added it to the requirements.
Should be fine to put in `startPlugins` as far as I'm aware, seems to be intended as a library and therefore have a light startup time, especially with none of its more complicated features enabled.
I can try and move it to be lazy and see if that has any issues, if that would be preferred.
- warning disappears
- …

utility/yazi-nvim: add missing dependency (snacks.nvim)

---

docs/release-notes/rl-0.8.md
modules/plugins/session/nvim-session-manager/nvim-session-manager.nix

Fixes `Error detected while processing VimEnter Autocommands for "*"` by
using an enum type for "autoload_mode" instead of a string.
See https://github.com/Shatur/neovim-session-manager/issues/135.
~~I've implemented this by just overwriting the `autoload_mode` attribute in `setupOpts` with the `//` operator. It looks a bit messy, but I couldn't think of a cleaner way to achieve it while still making good use of `toLuaObject`.~~
Not done using the `apply` parameter of `mkOption`.
You can check the change with the following commands, that run an instance of `nvf` from my fork without and with the fix commit respectively:
```bash
nix run "git+https://gist.github.com/TheColorman/022acefec3137a404a898731e3b211f3"
nix run "git+https://gist.github.com/TheColorman/f70ac01742c886ed475afff6d4f5e2bd …
```

session/nvim-session-manager: fix autoload_mode type

---

docs/release-notes/rl-0.8.md
modules/plugins/completion/blink-cmp/blink-cmp.nix
modules/plugins/completion/blink-cmp/config.nix
modules/plugins/utility/default.nix
modules/plugins/utility/direnv/config.nix
modules/plugins/utility/direnv/default.nix
modules/plugins/utility/direnv/direnv.nix
modules/plugins/utility/mkdir/config.nix
modules/plugins/utility/mkdir/default.nix
modules/plugins/utility/mkdir/mkdir.nix
modules/plugins/utility/nix-develop/config.nix
modules/plugins/utility/nix-develop/default.nix
modules/plugins/utility/nix-develop/nix-develop.nix
npins/sources.json

Adds a few very simple plugins I use, as well as options for blink-cmp that I find useful.
I can split this into a couple PRs if that would be preferred.
- [mkdir.nvim](https://github.com/jghauser/mkdir.nvim)
- [nix-develop.nvim](https://github.com/figsoda/nix-develop.nvim)
- [direnv.vim](https://github.com/direnv/direnv.vim)
Two blink-cmp options:
- `blink-cmp.sourcePlugins`, for arbitrary blink-cmp completion sources
- there is a three provided sources that I've tested, that are disabled by default.
I'm not sure how to indicate in the docs that they are present without making them
disappear as soon as any other sources are added.
- `blink-cmp.friendly-snippets.enable`, for an alternate snippet source
- friendly-snippets is automatically detected by blink-cmp, so it doesn't need the same …

mkdir.nvim, nix-develop.nvim, direnv.vim: init, blink-cmp: add source options, friendly-snippets source

---

docs/release-notes/rl-0.8.md
modules/neovim/init/autocmds.nix
modules/neovim/init/default.nix

Adds `vim.augroups` and `vim.autocmds` as Nix-native APIs for defining autocommands and autogroups in Nix. The implementation is a bit hacky, and relies on Lua instead of Nix for resolving auto{cmd,group} tables but should work as intended. Basic testing yields no errors, but I'll know for sure after I convert all of my autocommands to the new format.

neovim/init: add autocommand & autogroup APIs

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/cue.nix
modules/plugins/languages/default.nix

Add supports to `cue` language.
---

languages/cue: initial CUE language support

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/default.nix
modules/plugins/languages/helm.nix
modules/plugins/languages/yaml.nix

Depends on #676 and #680
Adds language support for Helm charts via `helm-ls` and `vim-helm`

languages/helm: Initial Helm chart language support

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/php.nix

This pull request includes an update to the `modules/plugins/languages/php.nix` file to add `intelephense` language server configuration for PHP.

language/php: add initial support for intelephense php lsp

---

docs/release-notes/rl-0.8.md
modules/plugins/completion/blink-cmp/blink-cmp.nix
modules/plugins/completion/blink-cmp/config.nix

It seems like this has been around since before #667, but I only just tried doing this.
Before this pr, doing the following breaks because it complains about `setupOpts.sources.providers.<built-in-source>.module` not being set.
```nix
config.vim.autocomplete.blink-cmp.setupOpts.sources.providers.<built-in-source>.attribute = value;
```
Likely caused by `providerType` option `module` not having a default.
I'm honestly not sure why this causes issues, but it refuses to eval unless it is set, so set it to the correct values.
The implementation does assume that the built-in source modules will not change, which seems relatively safe to me.
If they do, changing them is easy. …

completion/blink: don't break when modifying built-in sources.providers

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/default.nix
modules/plugins/utility/snacks-nvim/config.nix
modules/plugins/utility/snacks-nvim/default.nix
modules/plugins/utility/snacks-nvim/snacks-nvim.nix
npins/sources.json

Adds a module for [snacks.nvim](https://github.com/folke/snacks.nvim) under `vim.utility.snacks-nvim`. There are no defaults, as we are now trying to avoid default options as much as possible
Note that some of the healthchecks will warn the user about missing tools, e.g., lazygit. This is expected, as nvf wants to avoid bundling tools and increase the closure size. This can be solved by running `:checkhealth snacks` and adding the missing tools as you require them.
Closes #613

utiltiy/snacks-nvim: init module

---

docs/release-notes/rl-0.8.md
modules/plugins/lsp/lspsaga/config.nix
modules/plugins/lsp/lspsaga/lspsaga.nix
npins/sources.json

Points lspsaga to the new source, which is the repository by the original author now that he is back. With this update, comes breaking API changes to keybinds- so I removed them entirely. Users are invited to add their own keybinds using nvf's own API. Documentation has been updated.
We also lazyload lspsaga now :)

lsp/lspsaga: update source; lazyload; remove keybinds

---

modules/plugins/completion/nvim-cmp/config.nix
modules/plugins/completion/nvim-cmp/nvim-cmp.nix

Moves nvim-cmp's default sources to the option default, which makes them appear
on the documentation properly. This should also make it so that overriding the
default no longer requires `mkForce`.
Closes #701

completion/nvim-cmp: document default sources; allow override

---

docs/release-notes/rl-0.8.md
flake/legacyPackages/blink-cmp.nix
modules/plugins/completion/blink-cmp/blink-cmp.nix
modules/plugins/completion/blink-cmp/config.nix

Clean up build derivation for blink-cmp, based on nixpkgs variant. This pulls in
a patch that we probably should've vendored, but it will no longer be necessary
with the next update.
Also uses the new fetcher.
Possibly fixes #713

blink-cmp: apply Nix patch; use new fetcher

---

modules/plugins/diagnostics/nvim-lint/config.nix

fixes #732 #686 
can't tell if nvim-lint actually works, but at least it doesn't crash now

nvim-lint: fix config syntax

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/astro.nix
modules/plugins/languages/svelte.nix
modules/plugins/languages/ts.nix

i added conditions to launch eslint_d when root has one of these files:
- eslint.config.mjs
- eslint.config.js
- .eslintrc
- .eslintrc.js
- .eslintrc.json
- .eslintrc.yml

eslint_d: added conditions for launching eslint_d

---

docs/manual/configuring/custom-plugins/lazy-method.md
docs/release-notes/rl-0.8.md
modules/plugins/assistant/copilot/config.nix
modules/wrapper/lazy/config.nix
modules/wrapper/lazy/lazy.nix

related: #693 
creates a LazyFile user event based on LazyVim's LazyFile
---

lazy: create LazyFile user event, load copilot-lua on LazyFile

---

docs/manual/options.md

Add missing word in sentence: `let`.

docs: fix typo

---

docs/release-notes/rl-0.8.md
modules/plugins/diagnostics/nvim-lint/config.nix
modules/plugins/diagnostics/nvim-lint/nvim-lint.nix
modules/plugins/languages/astro.nix
modules/plugins/languages/bash.nix
modules/plugins/languages/css.nix
modules/plugins/languages/elixir.nix
modules/plugins/languages/fsharp.nix
modules/plugins/languages/go.nix
modules/plugins/languages/hcl.nix
modules/plugins/languages/kotlin.nix
modules/plugins/languages/markdown.nix
modules/plugins/languages/nim.nix
modules/plugins/languages/nix.nix
modules/plugins/languages/ocaml.nix
modules/plugins/languages/python.nix
modules/plugins/languages/r.nix
modules/plugins/languages/ruby.nix
modules/plugins/languages/rust.nix
modules/plugins/languages/sql.nix
modules/plugins/languages/svelte.nix
modules/plugins/languages/ts.nix
modules/plugins/languages/typst.nix
npins/sources.json

migrate from null-ls to conform/nvim-lint
This PR is free of breaking change, but I do want to do a refactor later to remove redundant options to "centralize" options to the conform/nvim-lint modules.
planned refactors:
- remove `<lang>.format.package` - should be set in conform
- change `<lang>.format.type` to accept a list, some languages need multiple formatters
---
[reaction]: …

languages: migrate to conform/nvim-lint

---

modules/plugins/git/gitsigns/config.nix
modules/plugins/lsp/null-ls/config.nix
modules/plugins/lsp/null-ls/null-ls.nix

Converts null-ls to the new setupOpts format now that the plugin has been updated and internal dependency is removed. Few breaking changes, but nothing that should concern the users as far as I'm aware.

lsp/null-ls: convert to new setupOpts format; get rid of prelude DAG

---

docs/release-notes/rl-0.8.md
modules/plugins/formatter/conform-nvim/conform-nvim.nix

Allow `null` which disables this functionality, as already described by the options.
This doesn't change the default which format both on and after save.
Also, there are a lot of completely unused inherits in the module, which I didn't clean up, but are probably worth noting.
- haven't tested the change directly in nvf, but I have been overriding the setup in my personal config to use `null` for a while
---
[reaction]: …

fix(formatter/conform-nvim): allow disabling format on/after save

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/telescope/telescope.nix

Applies the following fixes:
- Correctly nests "pickers" config under "telescope.setupOpts"
- Correctly nests "find_command" config under "telescope.setupOpts.pickers.find_files"
- Sets the find_command to mimic pre-fix behavior with "fd --type=file"
Closes #756 
--- …

telescope: correctly nest pickers under setupOpts

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/default.nix
modules/plugins/utility/oil-nvim/config.nix
modules/plugins/utility/oil-nvim/default.nix
modules/plugins/utility/oil-nvim/oil-nvim.nix
npins/sources.json

Add oil.nvim, the alternative file explorer to edit filesystems as a buffer.
Closes #722

utility/oil-nvim: init

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/oil-nvim/config.nix

fix: don't reference snacks in oil config

---

docs/release-notes/rl-0.8.md
modules/plugins/tabline/nvim-bufferline/config.nix
modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix

This PR adds catppuccin integration for bufferline
```
nvf.url = "github:venkyr77/nvf/catppuccin-bufferline-integration";
```
before adding integration
after adding integration
--- …

tabline/bufferline: add catppuccin integration

---

docs/release-notes/rl-0.8.md
modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix

This PR adds neo-tree integration for bufferline
```
nvf.url = "github:venkyr77/nvf/bufferline-neotree-integration";
```
before adding integration
after adding integration
--- …

tabline/bufferline: add neo-tree integration

---

docs/release-notes/rl-0.8.md
modules/plugins/ui/illuminate/illuminate.nix

This PR adds more applicable filetypes to illuminate denylist
```
nvf.url = "github:venkyr77/nvf/illuminate-denylist-fix";
```
before change
after change
"default" is not highlighted
--- …

ui/illuminate: add more applicable filetypes to denylist

---

docs/release-notes/rl-0.8.md
modules/plugins/mini/indentscope/config.nix
modules/plugins/mini/indentscope/indentscope.nix

This PR adds autocmd to disable indentscope in applicable filetypes
```
nvf.url = "github:venkyr77/nvf/indentscope-fix";
```
before change
after change
---

mini/indentscope: add autocmd to disable indentscope in applicable filetypes

---

docs/release-notes/rl-0.8.md
modules/plugins/lsp/config.nix
modules/plugins/lsp/module.nix

Fixes https://github.com/NotAShelf/nvf/issues/655
This PR adds option `config.vim.lsp.inlayHints.enable`
```
nvf.url = "github:venkyr77/nvf/inlay-hint-support";
```
with `config.vim.lsp.inlayHints.enable = false`,
with `config.vim.lsp.inlayHints.enable = true`,
---
[pull …

lsp: add inlayHints support

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/fzf-lua/fzf-lua.nix

fzf-lua will fail with error message if `fzf` is not installed system-wide
This PR removes this hard dependency by adding `fzf` to packages available for the wrapper
```
nvf.url = "github:venkyr77/nvf/fzf-lua-fix";
```
before,
after,
---
[pull requests you find …

utility/fzf-lua: remove hard dependency on fzf

---

modules/plugins/utility/fzf-lua/fzf-lua.nix

Followup from https://github.com/NotAShelf/nvf/pull/795
I missed `nix flake update` during testing after changing the type, the type is actually a string, not a package
```
nvf.url = "github:venkyr77/nvf/fzf-lua-type-fix";
```
tested with `config.vim.fzf-lua.enable = true` and `config.vim.fzf-lua.enable = false`.
---
[reaction]: …

utility/fzf-lua: fix type for fzf-bin

---

docs/release-notes/rl-0.8.md
modules/plugins/utility/telescope/telescope.nix

".git" is a regex, so because of the '.' it matches more than just the .git directory, so escape the dot to make it literal. Here, that's done with a '%'.

utility/telescope: fix ignore patterns

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/dart.nix

Without this dependency, loading a dart file will result in an error message and no LSP support or syntax highlighting.
---

languages/dart: add flutter-tools.nvim dependency plenary.nvim

---

docs/release-notes/rl-0.8.md
modules/plugins/diagnostics/nvim-lint/config.nix
modules/plugins/diagnostics/nvim-lint/nvim-lint.nix
modules/plugins/languages/astro.nix
modules/plugins/languages/svelte.nix
modules/plugins/languages/ts.nix
npins/sources.nix

This adds the ability to only lint when specific files are present.

nvim-lint: added required files support

---

modules/plugins/languages/go.nix

The default go formatter is the exact same as go LSP's formatter except slower, this PR disables
gofmt if LSP is enabled

languages/go: default disable gofmt if lsp is enabled

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/dart.nix

The commit messages should explain what I changed and why.
The color options currently don't work when nvim is transparent, so there will be another PR to fix that, or to update `flutter-tools.nvim` once https://github.com/nvim-flutter/flutter-tools.nvim/issues/466 is resolved.
--- …

languages/dart: address hidden dependencies of flutter-tools.nvim

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/python.nix

- Most dap configurations expect `"debugpy"` as the adapter name, not `"python"`.
- This causes breakages in the very common case in many python repositories which have their debug config set up in `.vscode/launch.json` with `type: "debugpy"` and not `type: "python"`.
- Most people with vscode will be configuring their `launch.json` as shown [here](https://code.visualstudio.com/docs/python/debugging#_set-configuration-options).
- nvim-dap will automatically use the configuration in `.vscode/launch.json` if it exists, thus to avoid errors for nvf users that are working on repositories containing this file, we should use the same adapter as well.
- While `"python"` makes more sense as it is more general, there are no other commonly used python daps so I think renaming it to this specific …

languages/python: change DAP name from "python" to "debugpy"

---

docs/release-notes/rl-0.8.md
modules/neovim/init/highlight.nix

The color options also allow color definitions in the form of color names.
---

highlight: fix color type

---

modules/plugins/languages/python.nix

- [this PR](https://github.com/NotAShelf/nvf/pull/841) changed the dap adaptor name for python from `"python"` to `"debugpy"` to conform with the common case where many `.vscode/launch.json`s will reference `"debugpy"`
- Unfortunately, I introduced a regression by mistakenly changing the dap configuration name to `debugpy` as well. While the dap adaptor name refers to the adaptor type, the dap configuration name refers to the language so I reverted that one line
- I initially missed this error since I only tested the PR in a repo containing a `launch.json` so it overrode the default config, but it was brought up in [this issue](https://github.com/NotAShelf/nvf/issues/850)
- This PR has been tested __both__ in a repo containing a `launch.json` and without

languages/python: fix python dap configuration regression

---

docs/release-notes/rl-0.8.md
modules/plugins/statusline/lualine/config.nix
modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix

More Integrations!
This PR adds,
1. `bufferline` offset for `snacks.explorer`
2. `lualine` extension for `snacks.picker`
References
1. https://github.com/folke/snacks.nvim/discussions/1340
2. https://github.com/folke/snacks.nvim/issues/1694
3. https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/extensions/nerdtree.lua
4. https://github.com/nvim-lualine/lualine.nvim/blob/master/lua/lualine/extensions/neo-tree.lua
```
nvf.url = "github:venkyr77/nvf/snacks-integrations";
```
before,
after,
- If …

utility/snacks-nvim: add lualine, bufferline extension / offset

---

lib/languages.nix
modules/neovim/init/default.nix
modules/neovim/init/lsp.nix
modules/plugins/languages/default.nix

- **lib/languages: add `lspOptions` submodule type for freeform LSP config**
- **lib/languages: add `root_marker` to `lspOptions` type**
- **neovim/lsp: init**
- **lib/languages: add explicit enable to LSP submodule**
- **lib/lua: deprecate old Lua helpers superseded by `toLuaObject`**
This exposes a low(er) level API for configuring LSPs _directly_ with the new
options provided by Neovim 0.11. The idea is to allow configuring LSPs without
relying on the inclusion of language modules into nvf, or allowing language
modules in user configurations.
The language modules still use the old API, and will be migrated in due time.
Changes here are split off to avoid withholding important additions to the
module system until all language modules are converted. Language modules, of
course, will …

neovim/lsp: expose low-level API

---

docs/manual/installation/custom-configuration.md

`tree-sitter` should be `treesitter`. `nix run` gives an error when using the example config verbatim.

fix: bad option in custom-config example

---

docs/release-notes/rl-0.8.md
modules/plugins/git/gitsigns/config.nix

this was the error before
```
error: A definition for option `home-manager.users.jacek.programs.nvf.settings.vim.lsp.null-ls.setupOpts.sources' is not of type `null or (list of (luaInline))'. Definition values:
- In `/nix/store/7zf02n9i01b02dvlqx54ksgllzrhxhck-source/modules/plugins/git/gitsigns/config.nix':
{
gitsigns-ca = {
_type = "lua-inline";
expr = ''
require("null-ls").builtins.code_actions.gitsigns
```

plugins/gitsigns: fix null-ls issue

---

modules/plugins/ui/breadcrumbs/breadcrumbs.nix
modules/plugins/ui/breadcrumbs/config.nix

I added missing Navbuddy mappings and cleaned up the module's option descriptions.
---

ui/breadcrumbs: update navbuddy

---

docs/release-notes/rl-0.8.md
modules/plugins/filetree/nvimtree/nvimtree.nix

This PR addresses the issues mentioned in #876:
1. Missing `right_align` option for icon placements.
2. Missing several icon type `*_placement` options for configuration.
I did as extensive of testing as I could, and you can see the changes were successful (using one of the new options, 
```nix
nvimTree.setupOpts.renderer.icons.diagnostics_placement = "right_align";
```
As shown below, it is working as expected:
---
[reaction]: …

filetree/nvimTree: add misising icon options

---

.github/labels.yml
.github/workflows/backport.yml
.github/workflows/labeler.yml

Based on the Nixpkgs CI, this creates a simplified workflow that allows us to
- tag changes based on the affected files
- backport changes to a target branch by specifying a backport label

ci: backport & labeler config

---

docs/release-notes/rl-0.8.md
modules/plugins/treesitter/default.nix
modules/plugins/treesitter/ts-textobjects/config.nix
modules/plugins/treesitter/ts-textobjects/default.nix
modules/plugins/treesitter/ts-textobjects/textobjects.nix
npins/sources.json

Not sure if there's a better way to make this load before mini.ai and after TS. Nothing seems to break even if mini.ai is disabled.
I also don't use any default config for the actual plugin, just the objects it provides with my mini.ai user config.

feat: add treesitter textobjects

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/markdown.nix
modules/plugins/languages/ruby.nix

added shopify's new lsp for ruby called `ruby-lsp` as a server option along side solargraph
Also updated the solargraph config to match all the other, with the fact that it can either be a package or list of strings

add ruby lsp as ruby server option

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/rust.nix

I don't think we want Conform to also do autoformatting. I am running into issues where it doesn't respect the `rustfmt.toml` file and will happily format according to the 2015 edition. The builtin `RustFmt` command also works and can be set up to autosave, but `rustaceanvim` includes `rust-analyzer` which will run `rustfmt` as well. 
All this to say, autoformatting still works without Conform and also doesn't break stuff.

fix: disable Conform for Rust

---

modules/plugins/assistant/codecompanion/config.nix

assistant/codecompanion: also add YAML tree-sitter grammar when enabled

---

modules/plugins/utility/yanky-nvim/config.nix

Fix assertion condition when checking yanky storage against the vim shada option.
---

fix(yanky-nvim): shada assertion condition

---

docs/release-notes/rl-0.8.md
modules/plugins/snippets/luasnip/config.nix
modules/plugins/snippets/luasnip/luasnip.nix

This adds `vim.snippets.luasnip.customSnippets.snipmate` as an option, allowing custom snippets to be added to the runtime dir.
Only snipmate is added as of now, but VSCode snippets should be easy enough to patch in.
---

snippets/luasnip: add the ability to add custom snippets

---

modules/neovim/init/clipboard.nix

nvf.settings.vim.clipboard.registers allows for either a string or a list of strings, but Neovim only accepts a string value. When a NVF user follows the options Appendix and passes a string, this results in an invalid Neovim config. Solved by updating the type to allow strings only.

Update vim.clipboard.registers type to str

---

docs/manual/tips/pure-lua-config.md

The example code in the [Pure Lua Configuration](https://notashelf.github.io/nvf/index.xhtml#sec-pure-lua-config)/[Pure Runtime Directory](https://notashelf.github.io/nvf/index.xhtml#sec-pure-nvf-runtime) section references the `vim.additionalRuntimeDirectories` option, which does not exist. The correct option is `vim.additionalRuntimePaths` (as seen in the [source](https://github.com/NotAShelf/nvf/blob/5bad5dd94ce5ea3b40b08d9e6802e69d02198d21/modules/wrapper/rc/options.nix#L31) and [docs](https://notashelf.github.io/nvf/options.html#opt-vim.additionalRuntimePaths)).
- If new …

doc: fix un-buildable example code in pure-lua-config section

---

configuration.nix
docs/release-notes/rl-0.8.md
modules/plugins/git/default.nix
modules/plugins/git/gitsigns/config.nix
modules/plugins/git/neogit/config.nix
modules/plugins/git/neogit/default.nix
modules/plugins/git/neogit/neogit.nix
npins/sources.json

This adds [Neogit](https://github.com/NeogitOrg/neogit), an interactive and powerful Git interface for Neovim, inspired by Magit.
It also changes the which-key group for gitsigns to `<leader>h` since its mappings were mostly under that prefix anyway and `<leader>g` makes sense to use for Neogit.
--- …

git/neogit: module init

---

docs/manual/configuring.md

previous relative link pointed to `nvf/options.html` on the repo instead of GH pages, causing 404
<!--
If your changes touch upon a portion of the codebase that you do not understand well, please make sure to consult
the maintainers on your changes. In most cases, making an issue before creating your PR will help you avoid duplicate
efforts in the long run. `git blame` might help you find out who is the "author" or the "maintainer" of a current
module by showing who worked on it the most.

doc: fix appendix link in ch-configuring section

---

docs/release-notes/rl-0.8.md
flake.lock
flake.nix

```
flake-parts's nixpkgs-lib input follows nvf's nixpkgs input to reduce
download size, and flake-utils's systems inputs follows nvf's systems
input to transitively leverage the pattern introduced in commit
fc8206e7a61d ("flake: utilize nix-systems for overridable flake
systems").
```
- **As a non-nvf user, my testing does not go beyond running `nix build .#{docs-html,docs-linkcheck,maximal,nix}` with the following temporary patch to avoid compiling `deno` from source:**
```diff
diff --git a/modules/plugins/languages/markdown.nix b/modules/plugins/languages/markdown.nix
index 23848835..e6337b5b 100644 …
```

flake: follow flake-parts and flake-utils inputs

---

modules/plugins/treesitter/treesitter.nix
modules/plugins/utility/harpoon/harpoon.nix

As per suggestion of `:h vim.loop`, "Use `vim.uv` instead."

treewide: `vim.loop` -> `vim.uv`

---

modules/plugins/lsp/otter/otter.nix

otter deprecated the set_filetype setting, making `set_filetype = true` the default (and only) behavior. Right now it gives a warning, but the setting will be removed in the next release of otter
(also, the PR template totally isn't working anymore, not sure what Github did)
(not tested yet becuase it's taking ages to build maximal rn and it's super late, but there's no reason why it should break. Will check back in the morning to test)

otter: remove deprecated setting

---

modules/plugins/treesitter/treesitter.nix

docs: missing `with` in `treesitter.nix`

---

default.nix
flake.lock
flake.nix
shell.nix

This PR adds a flake-less interface for Nix2 users, consumable without using flake inputs. It uses Lix's flake-compat implementation for a slightly faster store copy (benchmarked by eyeballing the difference in speed, trust me on this :pray:) and replaces the current formattere output with a treewide wrappere for compat with newer Nix versions.
CC @horriblename and @Soliprem for testing. I'll add usage documentation before merge.
Adresses #965

meta: add flake-compat & expose flakeless interface

---

modules/plugins/treesitter/treesitter.nix

docs: note for installing all grammars in `treesitter.nix`

---

configuration.nix
docs/release-notes/rl-0.8.md
modules/plugins/utility/default.nix
modules/plugins/utility/nvim-biscuits/config.nix
modules/plugins/utility/nvim-biscuits/default.nix
modules/plugins/utility/nvim-biscuits/nvim-biscuits.nix
npins/sources.json

Add `utility.nvim-biscuits` module. Adds the plugin nvim-biscuits, a rewrite of assorted biscuits.
Fixes #1034 
---

utility/nvim-biscuits: init

---

docs/release-notes/rl-0.8.md
modules/plugins/lsp/otter/config.nix

removes the now outdated warning
---

lsp/otter: remove conflict warning since 0.11 is now common

---

docs/release-notes/rl-0.8.md
modules/plugins/completion/blink-cmp/config.nix

Currently, regardless of whether nvim-cmp is enabled, nvim-cmp's sources are added as providers. If the nvim-cmp sources "buffer" or "path" are enabled they will override and break blink.cmp's default "path" and "buffer" sources.
This fixes the issue by only configuring nvim-cmp sources and providers when nvim-cmp is enabled and, if nvim-cmp is enabled, only configuring nvim-cmp compat providers that are not in the blink.cmp default sources.
The maximal config was not affected because both `languages.rust.crates.enable = true` and `snippets.luasnip.enable = true` set `autocomplete.nvim-cmp.sources`, overriding the default value of `{ nvim-cmp = null; buffer = "[Buffer]"; path = "[Path]"; }`.
[changelog]: …

fix(blink-cmp): Fix broken default sources

---

configuration.nix
docs/release-notes/rl-0.8.md
modules/plugins/languages/default.nix
modules/plugins/languages/qml.nix

Create the QML language module with treesitting, LSP, and formatting.
Author of #678 is no longer responding; therefore I opened this as a continuation.
- [qmlls](https://doc.qt.io/qt-6/qtqml-tooling-qmlls.html)
- [qmlformat](https://doc.qt.io/qt-6/qtqml-tooling-qmlformat.html)
--- …

languages/qml: init

---

docs/release-notes/rl-0.8.md

Clean up the release notes by merging entries separated when main was pulled into v0.8 and fixing my username link and display text.
---

docs: fixup release notes from main -> v0.8 merge

---

docs/release-notes/rl-0.8.md
modules/wrapper/lazy/lazy.nix

Maintainer note (horriblename): `skip ci` for unerlated formatting changes
Makes inline Lua enabled options evaluate to Lua instead of string literals.
Fixes #1109 
---

[skip ci] lazy: enabled option accepts luaInline instead of str

---

configuration.nix
docs/release-notes/rl-0.8.md
modules/plugins/lsp/default.nix
modules/plugins/lsp/harper-ls/config.nix
modules/plugins/lsp/harper-ls/default.nix
modules/plugins/lsp/harper-ls/harper-ls.nix

Add [harper-ls](https://github.com/automattic/harper) to the `vim.lsp` module.
---

lsp/harper-ls: init

---

docs/release-notes/rl-0.8.md
modules/plugins/languages/python.nix

`ruff check --fix` also formats python files, removing unused imports for example. I want an option that uses both `ruff format` and `ruff check --fix`.
---

languages/python: add formatter that combines `ruff format` with `ruff check --fix`

---

docs/release-notes/rl-0.8.md
modules/plugins/ui/default.nix
modules/plugins/ui/nvim-highlight-colors/config.nix
modules/plugins/ui/nvim-highlight-colors/default.nix
modules/plugins/ui/nvim-highlight-colors/nvim-highlight-colors.nix
npins/sources.json

This PR adds support for [nvim-highlight-colors](https://github.com/brenoprata10/nvim-highlight-colors), a plugin that uses highlight groups and/or virtual text to visually display the color being encoded as a string in various formats (i.e rgb(0 0 0), #fff, #ffffff, hsl(150deg 30% 40%), etc) in open buffers.
My personal motivation behind using this plugin and also writing this module is the ease with which it integrates with blink-cmp to display color highlighting in completion windows as well as it's virtual text which is super easy to configure to your desired style preferences. I am aware of the existing `nvim-colorizer` plugin which nvf already has a module for. I understand if the maintainers here don't think it's necessary to add and support another color highlighting plugin within …

ui/nvim-highlight-colors: init

---

docs/release-notes/rl-0.8.md
lib/dag.nix
modules/neovim/init/autocmds.nix
modules/neovim/init/lsp.nix
modules/plugins/languages/clang.nix
modules/plugins/languages/csharp.nix
modules/plugins/languages/dart.nix
modules/plugins/languages/haskell.nix
modules/plugins/languages/python.nix
modules/plugins/languages/rust.nix
modules/plugins/languages/ts.nix
modules/plugins/languages/yaml.nix
modules/plugins/lsp/config.nix

currently, we use `vim.lsp.config["*"].on_attach` to call `default_on_attach()` in order to set up LSP keybinds and other plugin integrations. This is a problem because
1. in 0.8, users who want to use lspconfig (via the `vim.lsp.config` interface) may get their on_attach function overridden by lspconfig. There's not really a good way to get both `default_on_attach` and the lspconfig-provided on_attach at the same time (there are some hacky ways that I'll omit for brevity)
2. we keep forgetting to call `default_on_attach` ourselves in language modules. To save us the trouble, I think we should just move `default_on_attach` to LspAttach autocmd instead
[hacking nvf]: …

attach LSP keybinds + other setup work in LspAttach

---

docs/release-notes/rl-0.8.md
modules/plugins/completion/blink-cmp/blink-cmp.nix

`inherit` as a value for the option `vim.autocomplete.blink-cmp.setupOpts.cmdline.keymap.preset` is valid as per [blink-cmp's documentation](https://cmp.saghen.dev/modes/cmdline.html). This is only true for alternate completion modes (mainly `cmdline`, but also potentially `terminal` AFAIK), allowing that mode to inherit the keymaps set for the default completion mode in blink-cmp. This is within `setupOpts` and is not related to the nvf-specific option `vim.autocomplete.blink-cmp.mappings` but it was still typed in nvf's blink-cmp module so this PR is updating that type. An excerpt from their docs details when to use this option:
>   If you want cmdline's behavior to match the default mode, try the following config:
>   
>   ```lua
>   cmdline = {
>     keymap = { preset = 'inherit' },
> …
```

completion/blink-cmp: added keymap "inherit" preset
