NotAShelf/nvf

extra.nix, flake.lock, flake.nix, flake/apps.nix, flake/legacyPackages.nix, flake/overlays.nix, flake/packages.nix, modules/default.nix
- split `neovimConfiguration` and `mainConfig` from flake.
=> flake.nix: transition to flake-parts

extra.nix, flake.lock, flake.nix, lib/types/plugins.nix, modules/lsp/config.nix, modules/lsp/default.nix, modules/lsp/elixir/config.nix, modules/lsp/elixir/default.nix, modules/lsp/elixir/elixir-tools.nix, modules/lsp/module.nix, modules/treesitter/treesitter.nix
This should implement elixir-ls and configure it using lspconfig. For now, the setup script for elixir-ls is obtained from the pkgs.elixir-ls path and not actually the flake input - needs to be corrected before merging.
=> feat: elixir language support

modules/theme/supported_themes.nix
fixes https://github.com/NotAShelf/neovim-flake/issues/54
=> fix: accept missing transparent attribute

docs/release-notes/rl-0.4.adoc, extra.nix, modules/terminal/toggleterm/config.nix, modules/terminal/toggleterm/toggleterm.nix
https://github.com/NotAShelf/neovim-flake/issues/46
a simple lazygit thing using toggleterm, derived from their help file
=> feat: lazygit integration

modules/completion/nvim-cmp/config.nix
fix: remove non-existent fallback function
=> fix tab not working

modules/lsp/config.nix
Should fix #62, but we need to have people test it.
=> fix formatting

docs/release-notes/rl-0.5.adoc, modules/theme/supported_themes.nix
first PR of v0.5! 
Adds transparency for tokyonight, I already tested it
=> feat: add transparency support for tokyonight

docs/release-notes/rl-0.5.adoc, modules/completion/nvim-cmp/config.nix
fix bug where cmp's abort and scrollDocs mapping wasn't working
=> fix cmp abort and scrollDocs keymap

docs/release-notes/rl-0.5.adoc, modules/notes/obsidian/config.nix, modules/notes/obsidian/obsidian.nix
Added daily not customization options for obsidian-nvim plugin
=> feat: add daily note options for obsidian

docs/release-notes/rl-0.5.adoc, flake.lock, flake.nix, lib/types/plugins.nix, modules/basic/config.nix, modules/basic/module.nix
closes #110
Hasn't been tested yet
=> Overhaul spell

modules/statusline/lualine/config.nix
boolean values should use boolToString instead
=> fix: use boolToString on boolean

lib/stdlib-extended.nix
same as mkMappingOption but allows for multiple keybinds
=> feat: add mkMultipleMappingOption

modules/languages/clang.nix
I need it for capturing structured bindings babe
=> feat: update clangd to 16

flake.nix
follow up to #147
This PR migrates to a [fork of nmd](https://github.com/horriblename/nmd) using mistune v3
Don't merge yet - I want to check if there are any unwanted changes to the output
~~I hate Python~~
=> Switch to nmd fork

docs/manual/languages.adoc, docs/release-notes/rl-0.5.adoc, modules/languages/default.nix, modules/languages/php.nix
Add php LSPs to neovim-flake 
I added PHPactor and Phan.
Please review and tell me what I should change
=> languages/php: init

modules/ui/noice/config.nix
fixes completion sources showing up every single time
=> ui/noice: disable messages by default

.github/workflows/cachix.yml, .github/workflows/check-docs.yml, .github/workflows/check.yml, .github/workflows/manual.yml
Closes #161 by switching to Determine Systems Nix Installer action in all workflows.
=> CI: use DetSys Nix Installer action

configuration.nix, docs/release-notes/rl-0.5.adoc, flake.lock, flake.nix, lib/types/plugins.nix, modules/visuals/config.nix, modules/visuals/visuals.nix
Adds highlight-undo, a plugin for highlighting undo/redo targets.
=> modules/visuals: add highlight-undo

configuration.nix, lib/languages.nix, lib/types/languages.nix, modules/languages/bash/bash.nix, modules/languages/bash/config.nix, modules/languages/bash/default.nix, modules/languages/default.nix
Adds a language server for bash.
=> languages/bash: add LSP

.github/README.md, .github/workflows/docker.yml, flake/packages.nix
Provides a simple docker build for the minimal `nix` configuration. More builds may be provided in the future.
=> flake: provide containerized builds

docs/release-notes/rl-0.6.md, flake.lock, flake.nix, lib/types/plugins.nix, modules/statusline/lualine/supported_themes.nix, modules/theme/supported_themes.nix
Added Gruvbox as a theme.
- New feature (non-breaking change which adds functionality)
I would love to paste in logs and screenshots of the logs. However, I got rate limited by GitHub, which made additional testing hard. The changes are small, and I didn't encounter a single problem. I'm just unable to run and build the flake with logs at the moment.
I also built the documentation to check if the new options were added. They were,
=> Theme: Added Gruvbox

modules/languages/java.nix
java lsp pacakge in nixpkgs changed the binary name, using getExe fix this situation
=> Fix java lsp not launching

modules/utility/telescope/config.nix, modules/utility/telescope/telescope.nix
=> utility/telescope: provide configurable vimgrep options

modules/default.nix
Directly wraps neovim using `wrapNeovimUnstable` instead of wrapping it through the `legacyWrapper` under `wrapNeovim`. 
I took a quick look at its commit history and it seems pretty stable despite its name. Regardless, I would appreciate a second opinion on this.
=> wrapper: migrate to `makeNeovimUnstable` wrapper

docs/release-notes/rl-0.6.md, modules/plugins/completion/nvim-cmp/config.nix, modules/plugins/completion/nvim-cmp/nvim-cmp.nix
=> completion/nvim-cmp: add `vim.autocomplete.autoComplete`

modules/plugins/session/nvim-session-manager/config.nix
must've messed up somewhere during rebase.
=> fix: bad import

modules/plugins/assistant/copilot/copilot.nix, modules/plugins/lsp/lsp-signature/lsp-signature.nix, modules/plugins/lsp/nvim-docs-view/nvim-docs-view.nix, modules/plugins/notes/obsidian/obsidian.nix, modules/plugins/notes/todo-comments/config.nix, modules/plugins/notes/todo-comments/todo-comments.nix, modules/plugins/projects/project-nvim/config.nix, modules/plugins/projects/project-nvim/project-nvim.nix, modules/plugins/terminal/toggleterm/toggleterm.nix
I might have made a mistake or two during rebase. This hopefully un-undoes all refactors
=> Fix rebase mistakes

docs/release-notes/rl-0.6.md, lib/types/plugins.nix
Not sure where to put the migration guide :shrug:
=> docs: more detail in setupOpts + migration guide

configuration.nix, docs/release-notes/rl-0.6.md, flake.nix, modules/plugins/assistant/chatgpt/chatgpt.nix, modules/plugins/assistant/chatgpt/config.nix, modules/plugins/assistant/chatgpt/default.nix, modules/plugins/assistant/default.nix
Redoes #242 with a minimal diff.
CC @ksonj for review.
=> assistant/chatgpt: Add jackMort/ChatGPT.nvim

configuration.nix
=> Disable neocord by default

lib/lua.nix, modules/plugins/visuals/fidget/fidget.nix
This makes the difference between str and luaInline a bit ambiguous so I'm removing it
=> Do not auto apply mkLuaInline

docs/release-notes/rl-0.7.md, modules/plugins/treesitter/config.nix
keybinds didn't work in visual mode
=> treesitter: fix ts incremental selection keybinds

docs/release-notes/rl-0.7.md, modules/plugins/statusline/lualine/config.nix, modules/plugins/statusline/lualine/lualine.nix
Successor PR of #290. 
- Cleans up Lualine module as per @balkenix's original PR.
- Fixes blending issue in section separators
- Fixes edited/read-only icons taking less space than they are supposed to.
=> lualine: increase theme compatibility; fix component definitions

modules/plugins/ui/colorizer/colorizer.nix, modules/plugins/ui/colorizer/config.nix
fixes #282 
~~Reverts API changes from the setupOpts PR, since it doesn't work well with this plugin~~
turns out I was looking at the unmaintained repo for a week and wondering why my code doesn't work. `setupOpts` is re-added
=> Fix colorizer

docs/manual/plugins.md, docs/manual/plugins/nodejs.md
A clear and concise description of the aim of your Pull Request.
Adds information about how to fix a reoccuring issue with nodeJS repos and auto-formatting
Please delete any options that are not relevant.
- Docs
Please try to check at least a majority of the checklist before opening your pull request. Exceptions to this will be reviewed on a case by case basis.
```
In 󱄅 framework at  .../neovim-flake on  main [$] 
❯ nix build .#docs-html
```
:clown:
=> Doc: add quirck about using nodejs

modules/plugins/autopairs/nvim-autopairs/config.nix, modules/plugins/completion/nvim-cmp/config.nix
=> modules/nvim-cmp: add edge case for autopairs in cr mapping

docs/release-notes/rl-0.7.md, lib/lua.nix, modules/plugins/tabline/nvim-bufferline/config.nix, modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix
That _should_ be all of them, I recommend double checking since my eyes could have slipped very easily.
Note: nvim starts without errors but bufferline doesn't appear.
=> tabline/bufferline: add missing options, add back bindings

docs/release-notes/rl-0.7.md, modules/plugins/ui/noice/config.nix, modules/plugins/ui/noice/noice.nix
=> Feat noice setup opts

configuration.nix, docs/default.nix, flake.nix, flake/modules/home-manager.nix, flake/modules/nixos.nix, flake/overlays.nix, flake/packages.nix, lib/configuration.nix, lib/default.nix, lib/stdlib-extended.nix, lib/types/custom.nix, lib/types/default.nix, modules/default.nix
=> treewide: refactor custom lib, merge lists in hm/nixos module

flake.lock, modules/default.nix
=> Use initViml instead of writeText

flake.lock, flake.nix, modules/default.nix
Okay actually the last one I'm done for real now
now I've got to write a README
=> gerg: switch to new repo

docs/release-notes/rl-0.7.md, flake.lock, flake.nix, modules/plugins/filetree/default.nix, modules/plugins/filetree/neo-tree/config.nix, modules/plugins/filetree/neo-tree/default.nix, modules/plugins/filetree/neo-tree/neo-tree.nix
=> plugins/neo-tree: init module

docs/release-notes/rl-0.7.md, modules/default.nix
- **modules: add helpers to display init.lua and its store path**
- **docs: update 0.7 release notes**
=> modules: add helper scripts

docs/release-notes/rl-0.5.md, docs/release-notes/rl-0.6.md, docs/release-notes/rl-0.7.md, flake.nix, modules/plugins/utility/default.nix, modules/plugins/utility/new-file-template/config.nix, modules/plugins/utility/new-file-template/default.nix, modules/plugins/utility/new-file-template/new-file-template.nix
no option to add templates because diniamo said so
they can be added by adding them to the runtime path under `lua/templates/`
=> plugins/new-file-template: init module

docs/release-notes/rl-0.7.md, lib/binds.nix, modules/neovim/mappings/config.nix, modules/neovim/mappings/options.nix, modules/wrapper/rc/config.nix
Reverts NotAShelf/nvf#352
I fucking hate git, sorry!
=> Revert "vim.maps rewrite"

docs/release-notes/rl-0.7.md, lib/binds.nix, modules/neovim/mappings/options.nix, modules/wrapper/rc/config.nix
re-add old vim.maps API to un-break builds while we work towards replacing the old one
=> Re-add old maps API

modules/plugins/theme/supported-themes.nix
fixes https://github.com/NotAShelf/nvf/pull/55#issuecomment-2308345626
deadnix? more like deadbraincells
=> theme: fix broken function signatures

docs/release-notes/rl-0.7.md, modules/plugins/languages/python.nix
New python LSPs, rejoice Python users!
=> languages/python: add basedpyright & python-lsp-server

docs/default.nix, modules/modules.nix
Common nix string interpolation L
=> docs: fix declerations

.github/README.md
Makes README more easily digestible, or overall more consistent.
Formats with deno-fmt again, and adds features section on top.
=> docs: re-format README; clean up sections

modules/wrapper/rc/config.nix
A clear and concise description of the aim of your Pull Request.
**If your pull request aims to fix an open issue or a present bug, please link the relevant issue below. If not, please remove this section**
Fixes #(issue)
Please delete any options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
Please try to check at least a majority of the checklist before opening your pull request. Exceptions to this will be reviewed on a case by case basis.
=> fix: missing function

docs/release-notes/rl-0.7.md, modules/plugins/filetree/neo-tree/config.nix
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Please delete any options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
=> plugins/neo-tree: fix file icons

modules/plugins/languages/elixir.nix
Fixes [#400](https://github.com/NotAShelf/nvf/issues/400)
Please delete any options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
Please try to check at least a majority of the checklist before opening your pull request. Exceptions to this will be reviewed on a case by case basis.
=> languages/elixir.nix: fix elixir-tools setup

docs/release-notes/rl-0.7.md, modules/neovim/mappings/config.nix, modules/neovim/mappings/options.nix, modules/wrapper/rc/config.nix
A second rewrite of keymaps cuz the last one doesn't allow different action on different modes
=> maps: allow same key on multiple mode

configuration.nix, docs/release-notes/rl-0.7.md
Enables lua for .#maximal.
---
=> configuration: enable lua for maximal

modules/plugins/completion/nvim-cmp/config.nix
Closes #418 
Fixes https://github.com/NotAShelf/nvf/pull/404#discussion_r1798623031
=> nvim-cmp: fix rewrite remnants

docs/release-notes/rl-0.7.md, modules/plugins/languages/css.nix, modules/plugins/languages/svelte.nix, modules/plugins/languages/ts.nix
Added [biome](https://github.com/biomejs/biome) support for formatting for Typescript, CSS and Svelte.
---
=> languages: add biome support for formatting

configuration.nix, docs/release-notes/rl-0.7.md, flake.lock, flake.nix, modules/plugins/utility/motion/default.nix, modules/plugins/utility/motion/precognition/config.nix, modules/plugins/utility/motion/precognition/default.nix, modules/plugins/utility/motion/precognition/precognition.nix
Adds [`precognition.nvim`](https://github.com/tris203/precognition.nvim).
Makes virtual text displaying motions underneath the cursor line in normal mode.
Closes my issue (#434).
---
=> utility: precognition.nvim

flake.lock, modules/plugins/filetree/neo-tree/config.nix, modules/plugins/utility/binds/which-key/config.nix, modules/plugins/utility/binds/which-key/default.nix, modules/plugins/utility/binds/which-key/which-key.nix, modules/plugins/visuals/default.nix
Updates all plugin inputs to their latest revisions.
which-key complains about keybind format in this PR.
=> flake: update all inputs

docs/manual/configuring/custom-plugins/configuring.md, docs/manual/configuring/custom-plugins/lazy-method.md
=> docs: fix typo

modules/wrapper/lazy/lazy.nix
=> lazy: remove redundant submodule

modules/plugins/theme/supported-themes.nix
Make all themes work by adding `...` to every theme attrset.
- [ X] I have tested, and self-reviewed my code.
- [X ] I ran **Alejandra** to format my code (`nix fmt`).
---
=> theme/supported-themes.nix: fix themes

modules/extra/deprecations.nix, modules/plugins/lsp/trouble/config.nix, modules/plugins/lsp/trouble/trouble.nix
=> trouble: fix binds

modules/plugins/languages/typst.nix
=> typst: added single file support for tinymist

docs/manual/installation/standalone/home-manager.md, docs/manual/installation/standalone/nixos.md
Just a simple typo fix for the docs.
---
=> docs: fix a typo in installation instructions

configuration.nix, modules/plugins/filetree/neo-tree/config.nix, modules/plugins/filetree/neo-tree/neo-tree.nix, modules/plugins/filetree/nvimtree/config.nix, modules/wrapper/lazy/config.nix
- ~~[ ] I have updated the [changelog] as per my changes.~~ (technically part of lz.n pr)
---
=> filetree/neo-tree: netrw hijack compat for lz.n

configuration.nix, docs/release-notes/rl-0.7.md, flake.lock, modules/plugins/languages/default.nix, modules/plugins/languages/nu.nix
=> modules/nu: init

configuration.nix, docs/release-notes/rl-0.7.md, flake.lock, flake/develop.nix, modules/plugins/languages/astro.nix, modules/plugins/languages/default.nix
Adds Astro to the list of languages supported. Also drops the shipped mnw version to fix an issue with node-based language servers.
---
=> languages/astro: init

configuration.nix, docs/release-notes/rl-0.7.md, modules/plugins/languages/default.nix, modules/plugins/languages/gleam.nix
Add TR and LSP support for gleam 
Done it all 
---
=> languages/gleam: init

modules/neovim/mappings/options.nix, modules/plugins/debugger/nvim-dap/config.nix, modules/wrapper/rc/config.nix
=> keymaps: fix null key problems

modules/plugins/comments/comment-nvim/config.nix
=> fix: bad comment keymaps

docs/release-notes/rl-0.8.md, flake.lock, flake.nix, modules/plugins/languages/typst.nix, release.json
- **meta: update release info (0.8)**
- **languages/typst: add `typst-preview.nvim` as an extension**
=> languages/typst: add live preview for tinymist

modules/wrapper/lazy/config.nix, modules/wrapper/lazy/lazy.nix
Useful for avoiding a million require calls in setupOpts.
=> wrapper/lazy: add beforeSetup option

flake.lock, modules/plugins/runner/run-nvim/config.nix
=> flake: update run.nvim

modules/wrapper/build/config.nix
Avoids the million `source` derivations in the system closure. Now they actually have a name and a version.
=> wrapper/build: improve noBuildPlug

docs/manual/manual.md, docs/manual/tips.md, docs/manual/tips/debugging-nvf.md, docs/manual/tips/offline-docs.md
Adds a brief section to highlight helpful tips.
=> docs: add helpful tips section

docs/release-notes/rl-0.8.md, flake.lock, flake.nix, modules/plugins/filetree/nvimtree/config.nix, modules/plugins/utility/default.nix, modules/plugins/utility/outline/aerial-nvim/aerial-nvim.nix, modules/plugins/utility/outline/aerial-nvim/config.nix, modules/plugins/utility/outline/aerial-nvim/default.nix, modules/plugins/utility/outline/default.nix
=> utility/aerial.nvim: init

docs/release-notes/rl-0.8.md, flake.lock, flake.nix, modules/plugins/ui/default.nix, modules/plugins/ui/nvim-ufo/config.nix, modules/plugins/ui/nvim-ufo/default.nix, modules/plugins/ui/nvim-ufo/nvim-ufo.nix
=> ui/nvim-ufo: init

docs/release-notes/rl-0.8.md, flake.lock, flake.nix, flake/legacyPackages.nix, modules/plugins/languages/nix.nix
Abandoned, archived and wildly outdated.
=> languages/nix: deprecate rnix language server option

docs/release-notes/rl-0.8.md, flake.lock, flake.nix, modules/plugins/utility/default.nix, modules/plugins/utility/fzf-lua/config.nix, modules/plugins/utility/fzf-lua/default.nix, modules/plugins/utility/fzf-lua/fzf-lua.nix
Add [fzf-lua](https://github.com/ibhagwan/fzf-lua)
=> utility/fzf-lua: init

modules/plugins/utility/telescope/telescope.nix
=> Telescope: remove invalid option `results_width`

docs/manual/hacking/additional-plugins.md
Adds missing `add` in the two `npins` commands, and fix a typo.
---
=> docs: missing npins subcommands

modules/wrapper/build/config.nix
=> flake: fix using blink-cmp package

npins/sources.json
Replacement for #622 as I had force-pushed it after closing.
=> npins: add conform-nvim, nvim-lint

configuration.nix, docs/release-notes/rl-0.8.md, modules/plugins/utility/default.nix, modules/plugins/utility/leetcode-nvim/config.nix, modules/plugins/utility/leetcode-nvim/default.nix, modules/plugins/utility/leetcode-nvim/leetcode-nvim.nix, npins/sources.json
Adding [leetcode.nvim](https://github.com/kawre/leetcode.nvim) plugin for coding competition fun from nvf (and cuz... leetcode)
closes issue #468
---
=> utility/leetcode-nvim: init

flake/modules/home-manager.nix
=> home-manager: forgot to remove trace

docs/release-notes/rl-0.8.md, modules/plugins/languages/go.nix
I have added options for configuring formatters for go.
- [gofmt](https://go.dev/blog/gofmt) (default)
- [golines](https://github.com/segmentio/golines)
- [gofumpt](https://github.com/mvdan/gofumpt)
---
=> languages/go: add gofmt, golines and gofumpt formatter

modules/wrapper/build/config.nix
=> languages/flutter: Update pin name for match

docs/release-notes/rl-0.8.md, modules/plugins/languages/default.nix, modules/plugins/languages/yaml.nix
=> languages/yaml: Init

modules/plugins/languages/yaml.nix
=> languages/yaml: Fix enableLSP/enableTreesitter

modules/plugins/lsp/otter/config.nix, npins/sources.json
=> otter: fix assert

.github/typos.toml, docs/release-notes/rl-0.8.md, modules/plugins/dashboard/alpha/alpha.nix, modules/plugins/dashboard/alpha/config.nix
Allows to configure alpha with nix. Supports predefined themes aswell as setting a custom layout and opts.
TODO:
- Example config
- Typed layout
=> Initial alpha.nvim nix implementation

.github/CODEOWNERS, .github/README.md
This should fix some of the CI related blockage, and allow PRs being merged with 1+ co-maintainer approval.
=> meta: add co-maintainers to CODEOWNERS

npins/sources.json, npins/sources.nix
=> fix: Update npins version

docs/release-notes/rl-0.8.md, modules/plugins/utility/motion/default.nix, modules/plugins/utility/motion/flash/config.nix, modules/plugins/utility/motion/flash/default.nix, modules/plugins/utility/motion/flash/flash.nix, npins/sources.json
A motion plugin, from Folke. https://github.com/folke/flash.nvim
Tested it locally and seems to work alright :) 
I'd like to be able to define additional setup opts, ideally as just a set to be converted into Lua; but I couldn't get it to work. Any help would be appreciated (could be a follow-on PR).
=> motion/flash-nvim: init

docs/release-notes/rl-0.8.md, modules/plugins/lsp/lspsaga/lspsaga.nix, modules/plugins/theme/supported-themes.nix
This PR adds catppuccin integration for lspsaga
```
nvf.url = "github:venkyr77/nvf/catppuccin-lspsaga-integration";
```
before adding integration
after adding integration
---
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Area …
=> lsp/lsp-aga: add catppuccin integration

docs/release-notes/rl-0.8.md, modules/plugins/languages/python.nix
python-lsp-server is under the namespace python3Packages, not under pkgs. This commit amends that by adding the namespace.
---
=> languages/python get python-lsp-server python3Packages

docs/release-notes/rl-0.8.md, modules/plugins/languages/ts.nix
=> language/ts: add conform and lint rules for tsx

docs/release-notes/rl-0.8.md, modules/plugins/git/default.nix, modules/plugins/git/gitlinker-nvim/config.nix, modules/plugins/git/gitlinker-nvim/default.nix, modules/plugins/git/gitlinker-nvim/gitlinker-nvim.nix, npins/sources.json
Not sure if you want this in the `git` category, or maybe under `utility` instead. Happy to move it. Not sure it totally fits in with `git`.
=> git/gitlinker-nvim: init

docs/release-notes/rl-0.8.md, modules/plugins/statusline/lualine/config.nix
This PR adds `neo-tree` extension to `lualine`
```
nvf.url = "github:venkyr77/nvf/lualine-neotree-extension";
```
before,
after,
---
=> statusline/lualine: add neo-tree extension

docs/release-notes/rl-0.8.md, modules/plugins/languages/astro.nix, modules/plugins/languages/svelte.nix, modules/plugins/languages/ts.nix
=> languages: fix eslint_d error on load

docs/release-notes/rl-0.8.md, modules/plugins/assistant/codecompanion/codecompanion-nvim.nix, modules/plugins/assistant/codecompanion/config.nix
=> assistant/codecompanion-nvim: fix nvim-cmp and defaults 

flake.lock, npins/sources.nix
=> flake: bump inputs

modules/neovim/init/autocmds.nix
=> autocmds: improve option descriptions

docs/release-notes/rl-0.8.md, modules/wrapper/rc/config.nix, modules/wrapper/rc/options.nix
=> rc: do not set options via luaConfigPre

docs/release-notes/rl-0.5.md, docs/release-notes/rl-0.6.md, docs/release-notes/rl-0.7.md
=> docs/release-notes: update jacekpoz to poz

configuration.nix, docs/release-notes/rl-0.8.md, modules/plugins/utility/binds/default.nix, modules/plugins/utility/binds/hardtime/config.nix, modules/plugins/utility/binds/hardtime/default.nix, modules/plugins/utility/binds/hardtime/hardtime.nix, npins/sources.json
Hello, this is my first Pull Request. I'm happy to contribute to the project! :)
I've added support for the [hardtime.nvim](https://github.com/m4xshen/hardtime.nvim) plugin, implementing basics two configuration options under vim.binds.hardtime:
- enable
- setupOpts
If you need me to change anything in the code, just let me know and I'll make the changes immediately!
=> binds/hardtime-nvim: init

flake.lock, modules/wrapper/build/config.nix
=> chore: update mnw

docs/release-notes/rl-0.8.md, modules/extra/deprecations.nix, modules/neovim/init/basic.nix
Deprecate `vim.scrollOffset` in favor of `vim.options.scrolloff`.
=> basic: deprecate vim.scrollOffset

configuration.nix, docs/release-notes/rl-0.8.md, modules/plugins/utility/binds/hardtime/config.nix, modules/plugins/utility/images/default.nix, modules/plugins/utility/images/img-clip/config.nix, modules/plugins/utility/images/img-clip/default.nix, modules/plugins/utility/images/img-clip/img-clip.nix, npins/sources.json, temp
[img-clip.nvim]: https://github.com/HakonHarnes/img-clip.nvim
Added [img-clip.nvim] plugin
---
=> utility/img-clip: init

docs/release-notes/rl-0.8.md, modules/plugins/theme/supported-themes.nix
=> themes/onedark: add missing transparency option 

flake/avante-nvim/default.nix
=> fix, Add dependencies needed for building Avante

modules/wrapper/build/config.nix
=> fix: pluginOverrides attempting to build

modules/neovim/init/diagnostics.nix
=> docs: working example for `vim.diagnostics.config.signs`

docs/release-notes/rl-0.8.md, modules/plugins/notes/neorg/config.nix, modules/plugins/notes/neorg/neorg.nix
blorb, nixpkgs moment. They deleted neorg grammars.
Currently doesn't build
=> languagaes/neorg: fix grammar packages

modules/neovim/init/diagnostics.nix
fix typo from "diagostics" to "diagnostics"
---
=> docs: fixed typo

modules/plugins/theme/supported-themes.nix, modules/plugins/utility/binds/which-key/config.nix
=> treewide: remove deprecated `isNull`

docs/release-notes/rl-0.8.md, modules/plugins/theme/supported-themes.nix, npins/sources.json
https://github.com/sainnhe/everforest
---
=> themes/everforest: init

modules/plugins/git/hunk-nvim/config.nix
Change-Id: I6a6a69645f227bef24e5e8481dcd4727623e710f
---
=> git/hunk-nvim: add missing UI dependency

modules/plugins/languages/wgsl.nix
=> languages/wgsl: fix binary path

modules/plugins/languages/haskell.nix
closes https://github.com/NotAShelf/nvf/issues/1031
---
=> languages/haskell: add missing comma after hls table

configuration.nix, docs/release-notes/rl-0.8.md, modules/plugins/utility/default.nix, modules/plugins/utility/undotree/config.nix, modules/plugins/utility/undotree/default.nix, modules/plugins/utility/undotree/undotree.nix, npins/sources.json
I was not able to build the maximal or nix packages without disabling typescript and markdown.
Fixes #1006 
---
=> utility/undotree: init

modules/plugins/languages/wgsl.nix
follow up to https://github.com/NotAShelf/nvf/pull/1029, updates the server attr name to match the correct one
---
=> languages/wgsl: make server name match package and binary name

docs/release-notes/rl-0.8.md, modules/plugins/languages/svelte.nix
=> languages/svelte: fix svelte-language-server not reloading .js/.ts files on change

docs/release-notes/rl-0.8.md
Add a missing period to the release notes.
---
=> docs: add missing period to release notes

docs/manual/configuring/languages.md, docs/release-notes/rl-0.8.md
=> docs: fix markdown formatting

flake/pkgs/by-name/avante-nvim/package.nix, modules/plugins/tabline/nvim-bufferline/config.nix, modules/plugins/tabline/nvim-bufferline/nvim-bufferline.nix, npins/sources.json
=> meta: bump plugins; fix bufferline

flake/develop.nix, modules/neovim/init/util.nix, modules/plugins/languages/clojure.nix, modules/plugins/languages/haskell.nix, modules/plugins/utility/motion/flash/config.nix
Run deadnix and statix to catch a few things lingering in the codebase.
---
=> deadnix + statix run
